// Browser-local AI Agent v2.1 — safe, human-approved edits only.
// No Ollama, no localhost bridge, no API key, no command execution.
const MODEL_ID='onnx-community/Qwen2.5-0.5B-Instruct';
const STORAGE_KEY='english-collocations-preview-v2';
let worker=null,requestId=0,busy=false,pending=[];
const esc=s=>String(s??'').replace(/[&<>\"']/g,a=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[a]));
function readRows(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return []}}
function writeRows(rows){localStorage.setItem(STORAGE_KEY,JSON.stringify(rows));window.dispatchEvent(new CustomEvent('preview-data-updated'));return rows}
function selectedIds(){return [...document.querySelectorAll('#body tr')].filter(tr=>tr.querySelector('.row-check')?.checked).map(tr=>String(tr.dataset.id))}
function selectedRows(){const ids=selectedIds(),rows=readRows();return ids.length?rows.filter(r=>ids.includes(String(r.id))):[]}
function ensureWorker(){return worker||(worker=new Worker('./ai-agent-worker.js?v=2.1',{type:'module'}))}
function callModel(messages){return new Promise((resolve,reject)=>{const id=++requestId,w=ensureWorker();const fn=e=>{if(e.data?.id!==id)return;w.removeEventListener('message',fn);e.data.ok?resolve(e.data.text):reject(new Error(e.data.error||'AI error'))};w.addEventListener('message',fn);w.postMessage({id,messages})})}
function json(text){const m=String(text).match(/\{[\s\S]*\}/);if(!m)throw Error('AI không trả về JSON hợp lệ');return JSON.parse(m[0])}
function styles(){if(document.getElementById('agentStyles'))return;const s=document.createElement('style');s.id='agentStyles';s.textContent=`.agent-card{padding:0!important;overflow:hidden}.agent-head{padding:14px 15px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}.agent-title{font-weight:850;font-size:15px}.agent-sub,.agent-note,.agent-status{font-size:11px;color:var(--muted);margin-top:5px}.agent-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px}.agent-actions button{font-size:11px;padding:8px}.agent-input{margin-top:10px}.agent-input textarea{width:100%;min-height:70px;resize:vertical}.agent-result{margin-top:9px;background:var(--card2);border:1px solid var(--line);border-radius:10px;padding:10px;font-size:12px;max-height:360px;overflow:auto}.agent-status.ok{color:var(--green)}.agent-status.err{color:var(--danger)}.agent-safe{font-size:10px;color:var(--green);margin-top:8px}.diff-item{border-top:1px solid var(--line);padding:9px 0}.diff-old{color:var(--danger);margin-top:5px}.diff-new{color:var(--green);margin-top:3px}.diff-actions{display:flex;gap:6px;margin-top:6px}.diff-actions button{font-size:10px;padding:5px 7px}.agent-apply{width:100%;margin-top:9px}.agent-apply[disabled]{opacity:.5}.agent-empty{color:var(--muted)}.agent-badge{font-size:10px;color:var(--green);margin-left:6px}`;document.head.appendChild(s)}
function status(t,k=''){const e=document.getElementById('agentStatus');if(e){e.className='agent-status '+k;e.textContent=t}}
function result(html){const e=document.getElementById('agentResult');if(e)e.innerHTML=html}
function renderAgent(){styles();const old=document.querySelector('.ai');if(!old)return;old.classList.add('agent-card');old.innerHTML=`<div class="agent-head"><div><div class="agent-title">🤖 AI Agent <span class="agent-badge">Browser local</span></div><div class="agent-sub">Chọn dòng → phân tích → xem diff → bạn duyệt → mới cập nhật dữ liệu</div></div></div><div class="agent-body"><div class="agent-actions"><button class="secondary" data-task="grammar">✓ Kiểm tra grammar</button><button class="secondary" data-task="spelling">✎ Kiểm tra chính tả</button><button class="secondary" data-task="natural">✨ Tự nhiên hơn</button><button class="secondary" data-task="translate">🇻🇳 Dịch</button><button class="secondary" data-task="cefr">📊 Phân tích CEFR</button><button class="secondary" data-task="examples">💡 Tạo ví dụ</button></div><div class="agent-input"><textarea id="agentPrompt" placeholder="Ví dụ: Kiểm tra grammar cho các dòng tôi đã chọn và đề xuất sửa..."></textarea><button id="agentAsk" style="width:100%;margin-top:7px">✨ Chạy Agent</button></div><div class="agent-status" id="agentStatus">Sẵn sàng · hãy chọn dòng rồi chạy tác vụ.</div><div class="agent-result" id="agentResult"><span class="agent-empty">🔒 Chưa có thay đổi nào. Agent không tự sửa dữ liệu.</span></div><div class="agent-safe">● AI chạy trong browser · không localhost · không API key · không Python · không thực thi lệnh</div><div class="agent-note">Model tải lần đầu và được browser cache. Các thay đổi chỉ được ghi khi bạn bấm Áp dụng.</div></div>`;old.querySelectorAll('[data-task]').forEach(b=>b.addEventListener('click',()=>runTask(b.dataset.task)));old.querySelector('#agentAsk').addEventListener('click',runFreeform)}
const taskPrompt={grammar:'Check grammar and spelling. If correction is needed, return correctedExample. Preserve meaning.',spelling:'Check spelling only. If correction is needed, return correctedExample. Preserve meaning.',natural:'Rewrite the example sentence to sound natural and professional workplace English. Preserve meaning.',translate:'Translate the example sentence into natural Vietnamese. Put the translation in correctedExample and do not change the English example.',cefr:'Estimate the CEFR level. Put the CEFR level in explanationVi and leave correctedExample empty.',examples:'Create a better workplace example sentence using the same collocation. Put it in correctedExample.'};
function targetText(r){return r.e||r.example||r.exampleEnglish||r.sentence||''}
function rowPrompt(task,r){return `You are a careful English-learning editor for Vietnamese professionals in UI/UX, technology, insurance and banking. Analyze ONLY this row. Return JSON only with keys: changed (boolean), correctedExample (string), explanationVi (string), confidence (number 0..1).\nTask: ${taskPrompt[task]}\nRow: ${JSON.stringify(r)}\nCurrent example: ${targetText(r)}`}
async function analyzeRows(task,rows){const out=[];for(let i=0;i<rows.length;i++){status(`Đang phân tích ${i+1}/${rows.length}…`);const text=await callModel([{role:'system',content:'Return valid JSON only. Never invent data. If no edit is needed, set changed false.'},{role:'user',content:rowPrompt(task,rows[i])}]);const a=json(text);if(a.changed&&a.correctedExample&&a.correctedExample.trim()!==targetText(rows[i]).trim())out.push({id:String(rows[i].id),oldText:targetText(rows[i]),newText:String(a.correctedExample).trim(),explanation:a.explanationVi||'',confidence:Math.max(0,Math.min(1,Number(a.confidence)||0))})}return out}
function renderDiff(items){pending=items;result(items.length?`<b>${items.length} đề xuất thay đổi</b>${items.map((x,i)=>`<div class="diff-item"><div><b>${i+1}.</b> ${esc(x.explanation)}</div><div class="diff-old">❌ ${esc(x.oldText)}</div><div class="diff-new">✅ ${esc(x.newText)}</div><div class="agent-note">Độ tin cậy: ${Math.round(x.confidence*100)}%</div><div class="diff-actions"><button class="secondary" data-skip="${i}">Bỏ qua</button></div></div>`).join('')}<button class="agent-apply" id="applyAll">✓ Áp dụng tất cả ${items.length} thay đổi</button>`:'<b>✓ Không có thay đổi cần áp dụng.</b>');document.getElementById('applyAll')?.addEventListener('click',applyAll);document.querySelectorAll('[data-skip]').forEach(b=>b.addEventListener('click',()=>{pending.splice(Number(b.dataset.skip),1);renderDiff(pending)}))}
function updateVisibleRow(id,newText){const tr=document.querySelector(`#body tr[data-id="${CSS.escape(String(id))}"]`);const el=tr?.querySelector('.editable[data-field="e"]');if(el){el.textContent=newText}}
function applyAll(){if(!pending.length)return;const approved=[...pending],rows=readRows(),map=new Map(approved.map(x=>[String(x.id),x]));const next=rows.map(r=>{const x=map.get(String(r.id));if(!x)return r;const copy={...r};if('e'in copy)copy.e=x.newText;else if('example'in copy)copy.example=x.newText;else if('exampleEnglish'in copy)copy.exampleEnglish=x.newText;else copy.e=x.newText;return copy});writeRows(next);approved.forEach(x=>updateVisibleRow(x.id,x.newText));pending=[];renderDiff([]);status(`✓ Đã áp dụng ${approved.length} thay đổi và lưu vào Preview`,'ok')}
async function runTask(task){if(busy)return;const rows=selectedRows();if(!rows.length){status('⚠️ Hãy chọn ít nhất một dòng trước.','err');return}busy=true;try{renderDiff(await analyzeRows(task,rows));status('✓ Phân tích xong · chưa sửa dữ liệu','ok')}catch(e){status('✕ '+e.message,'err');result('AI chưa sẵn sàng. Lần đầu model có thể cần thời gian để tải.')}finally{busy=false}}
async function runFreeform(){const input=document.getElementById('agentPrompt')?.value.trim();if(!input){status('⚠️ Nhập yêu cầu cho Agent.','err');return}const rows=selectedRows();if(!rows.length){status('⚠️ Hãy chọn các dòng cần Agent xử lý.','err');return}busy=true;try{const context=rows.map((r,i)=>`${i+1}. ${JSON.stringify(r)}`).join('\n');const text=await callModel([{role:'system',content:'You are a safe English learning agent. Analyze only provided rows. Do not execute commands, browse, access files, localhost, or secrets. Return concise Vietnamese guidance. Do not modify data.'},{role:'user',content:`${input}\n\nSelected rows:\n${context}`}]);result(`<div>${esc(text)}</div>`);status('✓ Hoàn tất · không tự sửa dữ liệu','ok')}catch(e){status('✕ '+e.message,'err')}finally{busy=false}}
function removeLegacyOllama(){document.querySelectorAll('.ollama-box,#testOllama,#stop,#chatStatus,.chat,.composer,.ai-head').forEach(e=>e.remove())}
function boot(){styles();removeLegacyOllama();renderAgent()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
