/* AI Agent Preview v6 — stable automatic example translation */
const DATA_KEY='english-collocations-preview-v2';
let autoBusy=new Set(),translateSeq=0,focusText=new WeakMap();
function rowsRead(){try{const x=JSON.parse(localStorage.getItem(DATA_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function rowsWrite(rows){localStorage.setItem(DATA_KEY,JSON.stringify(rows));window.dispatchEvent(new CustomEvent('preview-data-updated'));}
function rowText(r){return String(r?.e||r?.example||r?.exampleEnglish||r?.sentence||'').trim()}
function rowMeaning(r){return String(r?.em||r?.exampleMeaning||r?.translation||r?.meaningExample||'').trim()}
function updateRow(id,field,value){const rows=rowsRead();const next=rows.map(r=>String(r.id)===String(id)?{...r,[field]:value}:r);rowsWrite(next);return next.find(r=>String(r.id)===String(id))}
function cell(tr,field){return tr?.querySelector(`.editable[data-field="${field}"]`)||tr?.querySelector(`[data-field="${field}"]`)}
function setCell(tr,field,value){const el=cell(tr,field);if(!el)return;if('value'in el)el.value=value;else el.textContent=value;el.dispatchEvent(new Event('input',{bubbles:true}))}
function agentStatus(text,kind=''){const el=document.getElementById('agentStatus');if(el){el.textContent=text;el.className='agent-status '+kind}}
function translationToast(text,kind=''){let el=document.getElementById('autoTranslateStatus');if(!el){el=document.createElement('div');el.id='autoTranslateStatus';el.style.cssText='position:fixed;right:18px;bottom:18px;z-index:100000;max-width:380px;padding:10px 13px;border-radius:10px;background:#1c2738;color:#f4f7fb;border:1px solid #344257;box-shadow:0 10px 30px #0005;font:12px/1.4 system-ui';document.body.appendChild(el)}el.textContent=text;el.style.borderColor=kind==='error'?'#ff686d':'#36c98b';clearTimeout(el._timer);el._timer=setTimeout(()=>el.remove(),4500)}
function cleanTranslation(text,source){let s=String(text||'').replace(/```(?:json|text)?/gi,'').replace(/```/g,'').trim();try{const m=s.match(/\{[\s\S]*\}/);if(m){const j=JSON.parse(m[0]);s=String(j.translatedText||j.translation||s).trim()}}catch{} s=s.replace(/^(?:translation|translated text|bản dịch)\s*:\s*/i,'').trim();s=s.replace(/\s+/g,' ').trim();const unwanted=/^(bạn muốn|tôi có thể|tôi muốn giúp|bạn có muốn|điều này là đúng không|bạn muốn tôi)/i;const parts=s.split(/(?<=[.!?。！？])\s+/).map(x=>x.trim()).filter(Boolean);if(parts.length>1){const useful=parts.filter(x=>!unwanted.test(x));if(useful.length)s=useful[0]}const chunks=s.split(/(?<=[.!?。！？])\s+/).filter(Boolean);const seen=new Set(),kept=[];for(const c of chunks){const k=c.toLowerCase().replace(/\s+/g,' ').trim();if(!seen.has(k)){seen.add(k);kept.push(c)}}return kept.join(' ').trim().slice(0,800)}
async function myMemoryTranslate(sentence){const url='https://api.mymemory.translated.net/get?q='+encodeURIComponent(sentence)+'&langpair=en|vi';const res=await fetch(url,{method:'GET',mode:'cors',cache:'no-store'});if(!res.ok)throw new Error('MyMemory HTTP '+res.status);const data=await res.json();const t=String(data?.responseData?.translatedText||'').trim();if(!t)throw new Error('MyMemory returned empty text');return t}
async function googleTranslate(sentence){const url='https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=vi&dt=t&q='+encodeURIComponent(sentence);const res=await fetch(url,{method:'GET',mode:'cors',cache:'no-store'});if(!res.ok)throw new Error('Google translation HTTP '+res.status);const data=await res.json();const t=Array.isArray(data?.[0])?data[0].map(x=>x?.[0]||'').join('').trim():'';if(!t)throw new Error('Google returned empty text');return t}
async function localTranslate(sentence){return new Promise((resolve,reject)=>{const worker=new Worker('./ai-agent-worker.js?v=6',{type:'module'});const id=++translateSeq;const timer=setTimeout(()=>{worker.terminate();reject(new Error('Local AI timeout'))},20000);const done=(ok,value)=>{clearTimeout(timer);worker.terminate();ok?resolve(value):reject(new Error(value||'Local AI failed'))};worker.onmessage=e=>{const d=e.data||{};if(d.id!==id)return;if(d.type==='status'){if(d.stage==='loading')translationToast('⏳ Đang tải AI local lần đầu…');return}if(d.ok)done(!!String(d.text||'').trim(),String(d.text||''));else done(false,d.error)};worker.onerror=()=>done(false,'Local AI worker error');worker.postMessage({id,messages:[{role:'system',content:'Translate ONE English sentence into natural Vietnamese. Output ONLY the Vietnamese translation. Do not explain. Do not ask questions. Do not repeat any sentence. Stop after one translation.'},{role:'user',content:sentence}],batch:false})})}
async function translateExample(id,english){const key=String(id);if(autoBusy.has(key))return;autoBusy.add(key);translationToast('⏳ Đang tự động dịch câu ví dụ…');agentStatus('⏳ Đang tự động dịch nghĩa câu ví dụ…');try{const rows=rowsRead(),current=rows.find(r=>String(r.id)===key);if(!current)return;if(rowText(current)!==english)updateRow(id,'e',english);let translated='';const services=[['MyMemory',myMemoryTranslate],['Google',googleTranslate],['Browser AI',localTranslate]];for(const [name,fn] of services){try{const candidate=cleanTranslation(await fn(english),english);if(candidate){translated=candidate;break}}catch(e){console.warn('[AutoTranslate]',name,e)}}if(!translated)throw new Error('Không có dịch vụ dịch khả dụng');updateRow(id,'em',translated);setTimeout(()=>{const tr=document.querySelector(`#body tr[data-id="${CSS.escape(key)}"]`);setCell(tr,'em',translated)},80);translationToast('✓ Đã dịch tự động → NGHĨA CÂU VÍ DỤ');agentStatus('✓ Đã tự dịch và điền vào NGHĨA CÂU VÍ DỤ','ok')}catch(e){console.error('[AutoTranslate]',e);translationToast('⚠️ Dịch tự động lỗi: '+e.message,'error');agentStatus('⚠️ Không thể tự dịch: '+e.message,'err')}finally{autoBusy.delete(key)}}
function isExampleCell(el){return !!(el&&el.matches&&el.matches('.editable[data-field="e"]'))}
function bindAutoTranslation(){document.querySelectorAll('#body .editable[data-field="e"]').forEach(el=>{if(el.dataset.autoTranslationV6==='1')return;el.dataset.autoTranslationV6='1';el.addEventListener('focus',()=>{focusText.set(el,String(el.textContent||el.value||'').replace(/\s+/g,' ').trim())},{capture:true})})}
function globalBlurCapture(e){const el=e.target;if(!isExampleCell(el))return;const tr=el.closest('#body tr'),id=tr?.dataset.id;if(!id)return;const english=String(el.textContent||el.value||'').replace(/\s+/g,' ').trim();const before=focusText.get(el);if(english.length<3||english===before)return;setTimeout(()=>translateExample(id,english),150)}
function ensureAgentStatus(){if(document.getElementById('agentStatus'))return;const host=document.querySelector('.ai');if(!host)return;const s=document.createElement('div');s.className='agent-status';s.id='agentStatus';s.style.cssText='font-size:11px;color:var(--muted);margin:10px 14px';s.textContent='Sẵn sàng · sửa câu tiếng Anh rồi click ra ngoài để tự dịch.';host.appendChild(s)}
function bootAutoTranslation(){ensureAgentStatus();bindAutoTranslation();document.addEventListener('blur',globalBlurCapture,true);const body=document.getElementById('body');if(body&&!body.dataset.autoTranslationObserver){body.dataset.autoTranslationObserver='1';new MutationObserver(()=>bindAutoTranslation()).observe(body,{childList:true,subtree:true)}}window.addEventListener('preview-data-updated',()=>setTimeout(bindAutoTranslation,50))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(bootAutoTranslation,300));else setTimeout(bootAutoTranslation,300);
import('./auto-translate.js?v=2').catch(()=>{});
