// AI Agent overlay for English Collocations Preview.
// Browser-local inference only. No localhost, no API keys, no arbitrary tool execution.
const MODEL_ID = 'onnx-community/Qwen2.5-0.5B-Instruct';
const STORAGE_KEY = 'english-collocations-preview-v2';
let worker = null, requestId = 0, busy = false;
const esc=s=>String(s??'').replace(/[&<>\"']/g,a=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[a]));
function readRows(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return []}}
function selectedRows(){const ids=[...document.querySelectorAll('#body tr')].filter(tr=>tr.querySelector('.row-check')?.checked).map(tr=>Number(tr.dataset.id));const rows=readRows();return ids.length?rows.filter(r=>ids.includes(Number(r.id))):[]}
function ensureWorker(){return worker||(worker=new Worker('./ai-agent-worker.js',{type:'module'}))}
function callModel(messages){return new Promise((resolve,reject)=>{const id=++requestId,w=ensureWorker();const onMessage=e=>{if(e.data?.id!==id)return;w.removeEventListener('message',onMessage);e.data.ok?resolve(e.data.text):reject(new Error(e.data.error||'AI error'))};w.addEventListener('message',onMessage);w.postMessage({id,messages})})}
function parseJson(text){const m=String(text).match(/\{[\s\S]*\}/);if(!m)throw new Error('AI did not return JSON');return JSON.parse(m[0])}
function promptFor(task,row){return `You are a careful English-learning assistant for a Vietnamese professional working in UI/UX, technology, insurance and banking. Return concise, accurate results. Never invent facts.\nTask: ${task}\n\nJSON row:\n${JSON.stringify(row,null,2)}`}
function styles(){if(document.getElementById('agentStyles'))return;const s=document.createElement('style');s.id='agentStyles';s.textContent='.agent-card{padding:0!important;overflow:hidden}.agent-head{padding:13px 15px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:10px;align-items:center}.agent-title{font-weight:800}.agent-sub{font-size:11px;color:var(--muted)}.agent-body{padding:12px}.agent-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px}.agent-actions button{font-size:11px;padding:8px}.agent-input{margin-top:9px}.agent-input textarea{min-height:74px;resize:vertical}.agent-status{font-size:10px;color:var(--muted);margin-top:7px}.agent-status.ok{color:var(--green)}.agent-status.err{color:var(--danger)}.agent-result{margin-top:9px;background:var(--card2);border:1px solid var(--line);border-radius:10px;padding:10px;white-space:pre-wrap;font-size:12px;max-height:300px;overflow:auto}.agent-note{font-size:10px;color:var(--muted);margin-top:8px;line-height:1.45}.agent-safe{display:inline-flex;align-items:center;gap:5px;font-size:10px;color:var(--green);margin-top:8px}';document.head.appendChild(s)}
function setStatus(t,k=''){const e=document.getElementById('agentStatus');if(e){e.className='agent-status '+k;e.textContent=t}}
function setResult(t){const e=document.getElementById('agentResult');if(e)e.textContent=t}
function renderAgent(){styles();const old=document.querySelector('.ai');if(!old)return;old.classList.add('agent-card');old.innerHTML=`<div class="agent-head"><div><div class="agent-title">🤖 AI Agent <span class="model-pill">Browser local</span></div><div class="agent-sub">AI chạy độc lập trong trình duyệt · không Ollama · không API key</div></div></div><div class="agent-body"><div class="agent-actions"><button class="secondary" data-agent="grammar">✓ Grammar</button><button class="secondary" data-agent="spelling">✎ Chính tả</button><button class="secondary" data-agent="natural">✨ Tự nhiên hơn</button><button class="secondary" data-agent="translate">🇻🇳 Dịch</button><button class="secondary" data-agent="cefr">📊 CEFR</button><button class="secondary" data-agent="examples">💡 Tạo ví dụ</button></div><div class="agent-input"><textarea id="agentPrompt" placeholder="Ví dụ: Kiểm tra câu này và giải thích lỗi..."></textarea><button id="agentAsk" style="width:100%;margin-top:7px">Gửi cho Agent</button></div><div class="agent-status" id="agentStatus">Sẵn sàng · model sẽ tải lần đầu khi bạn dùng AI.</div><div class="agent-result" id="agentResult">🔒 Agent chỉ đọc dữ liệu Preview khi phân tích. Không mở Terminal, không gọi localhost, không thực thi lệnh.</div><div class="agent-safe">● Suy luận chạy trong browser</div><div class="agent-note">Lần đầu dùng AI có thể tải model về browser cache. Model: ${MODEL_ID}</div></div>`;old.querySelectorAll('[data-agent]').forEach(b=>b.addEventListener('click',()=>runTask(b.dataset.agent)));old.querySelector('#agentAsk').addEventListener('click',runFreeform)}
async function runTask(task){if(busy)return;busy=true;setStatus('Đang phân tích…');const rows=selectedRows(),target=rows[0]||readRows()[0];if(!target){setStatus('Bảng chưa có dữ liệu.','err');busy=false;return}try{const ins={grammar:'Check grammar. Return JSON with correctedEnglish, explanationVi, confidence.',spelling:'Check spelling. Return JSON with correctedEnglish, explanationVi, confidence.',natural:'Rewrite naturally for professional workplace English. Return JSON with improvedEnglish, explanationVi, confidence.',translate:'Translate the example sentence to natural Vietnamese. Return JSON with translationVi, confidence.',cefr:'Estimate CEFR level. Return JSON with cefr, explanationVi, confidence.',examples:'Create one natural workplace example using the collocation. Return JSON with exampleEnglish, translationVi, confidence.'}[task];const text=await callModel([{role:'system',content:'You are a precise English tutor. Output valid JSON only.'},{role:'user',content:promptFor(ins,target)}]);setResult(JSON.stringify(parseJson(text),null,2));setStatus('✓ Phân tích xong','ok')}catch(e){setStatus('✕ '+e.message,'err');setResult('AI chưa sẵn sàng. Có thể model đang được tải lần đầu hoặc WebGPU không khả dụng.')}finally{busy=false}}
async function runFreeform(){if(busy)return;const input=document.getElementById('agentPrompt')?.value.trim();if(!input)return;busy=true;const rows=selectedRows();const context=(rows.length?rows:readRows().slice(0,10)).map((r,i)=>`${i+1}. ${r.c||''} | ${r.m||''} | ${r.t||''} | ${r.e||''} | ${r.em||''}`).join('\n');setStatus('Đang suy luận…');try{const text=await callModel([{role:'system',content:'You are a safe English learning agent. Analyze only the provided text. Do not execute commands, browse, access files, or request secrets. Answer in Vietnamese with useful English examples.'},{role:'user',content:`${input}\n\nContext from Preview table:\n${context}`}]);setResult(text);setStatus('✓ Hoàn tất','ok')}catch(e){setStatus('✕ '+e.message,'err')}finally{busy=false}}
function boot(){document.querySelectorAll('.ollama-box,#testOllama,#stop').forEach(e=>e.remove());renderAgent()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
