const parse=(items)=>items.map(x=>{const [c,v,cefr='']=x.split('|');return {c:c.trim(),v:v.trim(),cefr:cefr.trim().toUpperCase(),source:'local-expanded'}});

export const EXPANDED_SUGGESTIONS = Object.freeze(parse([
  'accept feedback|tiếp nhận phản hồi|B1','address user needs|giải quyết nhu cầu người dùng|B2','align with business goals|phù hợp với mục tiêu kinh doanh|B2','apply best practices|áp dụng các thông lệ tốt|B2','ask for clarification|yêu cầu làm rõ|B1','avoid unnecessary steps|tránh các bước không cần thiết|B1','build customer trust|xây dựng niềm tin khách hàng|B1',
  'carry out research|tiến hành nghiên cứu|B2','clarify the requirements|làm rõ các yêu cầu|B1','collect user feedback|thu thập phản hồi người dùng|B1','compare the options|so sánh các lựa chọn|B1','complete a task|hoàn thành một nhiệm vụ|A2','conduct a user interview|thực hiện phỏng vấn người dùng|B2','confirm the details|xác nhận các chi tiết|B1',
  'consider user needs|cân nhắc nhu cầu người dùng|B1','create a user flow|tạo luồng người dùng|B2','define the scope|xác định phạm vi|B2','deliver a solution|cung cấp một giải pháp|B2','describe the problem|mô tả vấn đề|A2','determine the cause|xác định nguyên nhân|B1','develop a roadmap|xây dựng lộ trình|B2',
  'discuss next steps|thảo luận các bước tiếp theo|B1','document the process|ghi lại quy trình|B1','draw a conclusion|rút ra kết luận|B1','ensure data quality|đảm bảo chất lượng dữ liệu|B2','establish a process|thiết lập một quy trình|B2','evaluate user behavior|đánh giá hành vi người dùng|B2','exceed expectations|vượt kỳ vọng|B2',
  'expand the scope|mở rộng phạm vi|B2','explore an option|khám phá một lựa chọn|B1','finalize the design|hoàn thiện thiết kế|B2','follow a process|tuân theo một quy trình|B1','follow up on|theo dõi / tiếp tục xử lý|B1','gather user insights|thu thập hiểu biết từ người dùng|B2','handle a request|xử lý một yêu cầu|B1',
  'identify user pain points|xác định điểm khó khăn của người dùng|B2','improve accessibility|cải thiện khả năng tiếp cận|B2','improve usability|cải thiện tính khả dụng|B2','increase user engagement|tăng mức độ tương tác của người dùng|B2','keep users informed|giữ người dùng được cập nhật|B1','launch a new version|ra mắt phiên bản mới|B1','learn from feedback|rút kinh nghiệm từ phản hồi|B1',
  'make an adjustment|thực hiện một điều chỉnh|B1','make an assumption|đưa ra một giả định|B2','make a recommendation|đưa ra khuyến nghị|B2','meet customer needs|đáp ứng nhu cầu khách hàng|B1','meet business goals|đạt mục tiêu kinh doanh|B1','move forward with|tiếp tục triển khai với|B2','narrow down the options|thu hẹp các lựa chọn|B2',
  'outline the requirements|phác thảo các yêu cầu|B2','plan ahead|lên kế hoạch trước|B1','prepare for a meeting|chuẩn bị cho một cuộc họp|A2','prioritize user needs|ưu tiên nhu cầu người dùng|B2','raise a concern|nêu mối quan ngại|B2','reduce friction|giảm sự cản trở|B2','remove a barrier|loại bỏ rào cản|B1',
  'resolve a blocker|giải quyết điểm nghẽn|B2','respond to feedback|phản hồi ý kiến|B1','review the results|xem xét kết quả|A2','run a usability test|tiến hành kiểm thử khả dụng|B2','set clear expectations|đặt kỳ vọng rõ ràng|B1','share an update|chia sẻ thông tin cập nhật|A2','simplify the interface|đơn giản hóa giao diện|B2',
  'solve a user problem|giải quyết vấn đề của người dùng|B1','start a discussion|bắt đầu một cuộc thảo luận|B1','test an assumption|kiểm thử một giả định|B2','track user behavior|theo dõi hành vi người dùng|B2','understand the context|hiểu bối cảnh|B1','validate an idea|xác thực một ý tưởng|B2','work toward a goal|hướng tới một mục tiêu|B1',

  'approve a loan|phê duyệt khoản vay|B1','assess credit risk|đánh giá rủi ro tín dụng|B2','authorize a payment|phê duyệt khoản thanh toán|B2','bank account details|thông tin tài khoản ngân hàng|A2','banking services|dịch vụ ngân hàng|A2','borrow money|vay tiền|A2','calculate interest|tính lãi suất|B1',
  'check account activity|kiểm tra hoạt động tài khoản|B1','close an account|đóng tài khoản|A2','credit card limit|hạn mức thẻ tín dụng|B1','credit risk assessment|đánh giá rủi ro tín dụng|B2','credit score|điểm tín dụng|B1','customer onboarding|quy trình tiếp nhận khách hàng mới|B2','debit card payment|thanh toán bằng thẻ ghi nợ|B1',
  'deposit money|gửi tiền|A2','digital banking|ngân hàng số|B1','direct debit|ghi nợ trực tiếp|B2','exchange rates|tỷ giá hối đoái|B1','financial advice|tư vấn tài chính|B1','financial institution|tổ chức tài chính|B1','financial product|sản phẩm tài chính|B1',
  'fund transfer|chuyển tiền|B1','handle transactions|xử lý giao dịch|B1','increase the credit limit|tăng hạn mức tín dụng|B2','interest rate|lãi suất|B1','loan application|đơn đăng ký khoản vay|B1','loan approval|phê duyệt khoản vay|B1','loan repayment|hoàn trả khoản vay|B2',
  'manage an account|quản lý tài khoản|A2','make a bank transfer|thực hiện chuyển khoản|B1','make a deposit|gửi tiền / nộp tiền|B1','monitor account activity|theo dõi hoạt động tài khoản|B2','open a bank account|mở tài khoản ngân hàng|A2','payment gateway|cổng thanh toán|B2','payment request|yêu cầu thanh toán|B1',
  'process a loan application|xử lý hồ sơ vay|B2','protect customer data|bảo vệ dữ liệu khách hàng|B2','report a suspicious transaction|báo cáo giao dịch đáng ngờ|B2','review a credit application|xem xét hồ sơ tín dụng|B2','secure online banking|bảo mật ngân hàng trực tuyến|B2','transfer funds|chuyển tiền|B1','verify account ownership|xác minh quyền sở hữu tài khoản|B2',

  'assess insurance needs|đánh giá nhu cầu bảo hiểm|B2','calculate a premium|tính phí bảo hiểm|B2','claim settlement|giải quyết bồi thường|B2','claim status|trạng thái yêu cầu bồi thường|B1','coverage limit|giới hạn bảo hiểm|B1','coverage period|thời hạn bảo hiểm|B1','customer policy|hợp đồng / chính sách của khách hàng|B1',
  'file an insurance claim|nộp yêu cầu bồi thường bảo hiểm|B2','insurance coverage|phạm vi bảo hiểm|B1','insurance premium|phí bảo hiểm|B1','issue a policy|phát hành hợp đồng bảo hiểm|B2','manage a claim|quản lý yêu cầu bồi thường|B2','policy coverage|phạm vi bảo hiểm của hợp đồng|B1','policy renewal|gia hạn hợp đồng|B1',
  'process an insurance claim|xử lý yêu cầu bồi thường bảo hiểm|B2','provide insurance coverage|cung cấp phạm vi bảo hiểm|B2','renew an insurance policy|gia hạn hợp đồng bảo hiểm|B1','risk profile|hồ sơ rủi ro|B2','underwrite a policy|thẩm định bảo hiểm cho hợp đồng|C1','underwriting process|quy trình thẩm định bảo hiểm|C1','valid insurance policy|hợp đồng bảo hiểm còn hiệu lực|B1',

  'achieve project goals|đạt mục tiêu dự án|B1','assign a task|giao một nhiệm vụ|B1','break down a task|chia nhỏ nhiệm vụ|B1','carry out a task|thực hiện nhiệm vụ|B1','complete a milestone|hoàn thành một mốc quan trọng|B2','coordinate a project|điều phối dự án|B2','deliver on time|hoàn thành đúng hạn|B1',
  'estimate project effort|ước tính công sức dự án|B2','extend the timeline|kéo dài tiến độ|B1','follow up with a client|theo dõi / liên hệ tiếp với khách hàng|B1','keep a project on track|giữ dự án đúng tiến độ|B2','manage project risks|quản lý rủi ro dự án|B2','meet project milestones|đạt các mốc dự án|B2','project kickoff|khởi động dự án|B2',
  'project status|trạng thái dự án|A2','project dependencies|các phụ thuộc của dự án|B2','project deliverables|các hạng mục bàn giao của dự án|B2','project requirements|yêu cầu dự án|B1','track project progress|theo dõi tiến độ dự án|B1','work on priorities|làm việc theo các ưu tiên|B1','work toward completion|hướng tới hoàn thành|B1',

  'access user data|truy cập dữ liệu người dùng|B1','deploy a release|triển khai một bản phát hành|B2','fix a bug|sửa lỗi|A2','handle an error|xử lý lỗi|A2','improve system stability|cải thiện độ ổn định hệ thống|B2','integrate an API|tích hợp một API|B2','manage access rights|quản lý quyền truy cập|B2',
  'monitor system health|theo dõi tình trạng hệ thống|B2','push a release|đẩy một bản phát hành|B2','release a feature|phát hành một tính năng|B1','resolve a technical issue|giải quyết vấn đề kỹ thuật|B2','run automated tests|chạy kiểm thử tự động|B2','scale the system|mở rộng quy mô hệ thống|B2','secure the system|bảo mật hệ thống|B1',
  'set up an environment|thiết lập môi trường|B1','support a legacy system|hỗ trợ hệ thống cũ|B2','track a bug|theo dõi lỗi|A2','troubleshoot an issue|khắc phục sự cố|B2','update the system|cập nhật hệ thống|A2','upgrade the platform|nâng cấp nền tảng|B2','version control|quản lý phiên bản|B2',

  'design a user flow|thiết kế luồng người dùng|B2','design a wireframe|thiết kế wireframe|B1','conduct usability testing|thực hiện kiểm thử khả dụng|B2','create a prototype|tạo nguyên mẫu|B1','define a user journey|xác định hành trình người dùng|B2','document design decisions|ghi lại các quyết định thiết kế|B2','establish a design system|thiết lập hệ thống thiết kế|B2',
  'evaluate a prototype|đánh giá nguyên mẫu|B2','gather design feedback|thu thập phản hồi về thiết kế|B2','improve the user flow|cải thiện luồng người dùng|B2','iterate on a design|lặp lại và cải tiến thiết kế|B2','map the user journey|lập bản đồ hành trình người dùng|B2','refine the interface|tinh chỉnh giao diện|B2','test a prototype|kiểm thử nguyên mẫu|B1',
  'test the user flow|kiểm thử luồng người dùng|B1','understand user behavior|hiểu hành vi người dùng|B2','use a design system|sử dụng hệ thống thiết kế|B1','validate the design|xác thực thiết kế|B2','visualize the data|trực quan hóa dữ liệu|B2','work with constraints|làm việc với các ràng buộc|B2','write UX copy|viết nội dung UX|B2',

  'attend a workshop|tham dự workshop|A2','book a meeting room|đặt phòng họp|A2','bring up an issue|nêu một vấn đề|B1','cancel a meeting|hủy cuộc họp|A2','chair a meeting|chủ trì cuộc họp|B2','come to an agreement|đi đến thỏa thuận|B1','confirm availability|xác nhận có thời gian|B1',
  'follow up after a meeting|theo dõi sau cuộc họp|B2','join a video call|tham gia cuộc gọi video|A2','leave a meeting|rời cuộc họp|A2','move a meeting|dời cuộc họp|A2','send meeting notes|gửi biên bản cuộc họp|A2','share meeting notes|chia sẻ ghi chú cuộc họp|A2','take meeting notes|ghi chú trong cuộc họp|A2',
  'talk through an issue|trao đổi kỹ về một vấn đề|B2','wrap up a meeting|kết thúc cuộc họp|B2','write an agenda|viết chương trình họp|A2','work through a problem|cùng xử lý một vấn đề|B2','agree on priorities|thống nhất về các ưu tiên|B1','clarify a point|làm rõ một điểm|B1','make a suggestion|đưa ra một đề xuất|B1',

  'answer a question|trả lời một câu hỏi|A1','ask a question|đặt một câu hỏi|A1','ask for help|nhờ giúp đỡ|A1','ask for permission|xin phép|A2','call a customer|gọi cho khách hàng|A2','deal with a complaint|xử lý khiếu nại|B1','explain a process|giải thích một quy trình|B1',
  'give clear instructions|đưa ra hướng dẫn rõ ràng|B1','give someone an update|cập nhật thông tin cho ai đó|B1','help a customer|giúp khách hàng|A1','keep someone updated|giữ ai đó được cập nhật|B1','make a request|đưa ra yêu cầu|A2','provide an explanation|đưa ra lời giải thích|B1','respond to a request|phản hồi một yêu cầu|B1',
  'solve a complaint|giải quyết khiếu nại|B1','speak with a customer|trao đổi với khách hàng|A2','take a message|nhận lời nhắn|A2','transfer a call|chuyển cuộc gọi|A2','understand the request|hiểu yêu cầu|A2','follow up on a request|theo dõi một yêu cầu|B1','handle customer questions|xử lý câu hỏi của khách hàng|B1',

  'check your email|kiểm tra email|A1','compose an email|soạn email|B1','draft an email|soạn nháp email|B1','forward an email|chuyển tiếp email|A2','get back to someone|phản hồi ai đó sau|B1','include an attachment|đính kèm tệp|A2','read an email|đọc email|A1',
  'reply to an email|trả lời email|A2','send an email|gửi email|A1','send a reminder|gửi lời nhắc|A2','share an attachment|chia sẻ tệp đính kèm|A2','write a follow-up email|viết email theo dõi|B1','write a polite email|viết email lịch sự|B1','write a subject line|viết tiêu đề email|B1',

  'analyze user data|phân tích dữ liệu người dùng|B2','analyze the results|phân tích kết quả|B1','base a decision on|dựa quyết định vào|B2','collect evidence|thu thập bằng chứng|B1','draw insights|rút ra hiểu biết|B2','find a pattern|tìm ra một mô hình|B1','interpret the results|diễn giải kết quả|B2',
  'look for a trend|tìm xu hướng|B1','measure user satisfaction|đo mức độ hài lòng của người dùng|B2','review the data|xem xét dữ liệu|A2','run an analysis|thực hiện phân tích|B2','spot a problem|nhận ra một vấn đề|B1','support a conclusion|hỗ trợ một kết luận|B2','test a hypothesis|kiểm định một giả thuyết|B2',

  'apply a policy|áp dụng chính sách|B1','comply with regulations|tuân thủ quy định|B2','conduct a compliance check|thực hiện kiểm tra tuân thủ|C1','ensure regulatory compliance|đảm bảo tuân thủ quy định|C1','follow company policy|tuân theo chính sách công ty|B1','manage compliance risks|quản lý rủi ro tuân thủ|C1','meet regulatory requirements|đáp ứng yêu cầu quy định|C1',
  'monitor compliance|theo dõi việc tuân thủ|B2','pass an audit|vượt qua một cuộc kiểm toán|B2','perform an audit|thực hiện kiểm toán|B2','prepare for an audit|chuẩn bị cho kiểm toán|B2','report a compliance issue|báo cáo vấn đề tuân thủ|C1','review a policy|xem xét chính sách|B1','update a policy|cập nhật chính sách|B1',

  'build a relationship|xây dựng mối quan hệ|B1','build team trust|xây dựng niềm tin trong nhóm|B2','collaborate with stakeholders|hợp tác với các bên liên quan|B2','communicate clearly|giao tiếp rõ ràng|B1','give constructive feedback|đưa phản hồi mang tính xây dựng|B2','handle a disagreement|xử lý bất đồng|B2','keep the team aligned|giữ đội ngũ thống nhất|B2',
  'manage expectations|quản lý kỳ vọng|B2','reach a compromise|đạt thỏa hiệp|B2','resolve a disagreement|giải quyết bất đồng|B2','share responsibility|chia sẻ trách nhiệm|B1','strengthen a relationship|củng cố mối quan hệ|B2','work as a team|làm việc theo nhóm|A2','work cross-functionally|làm việc liên phòng ban|B2',

  'achieve a result|đạt kết quả|A2','achieve a milestone|đạt một cột mốc|B1','deliver a result|đạt / cung cấp kết quả|B1','drive growth|thúc đẩy tăng trưởng|B2','generate value|tạo ra giá trị|B2','increase efficiency|tăng hiệu quả|B1','improve productivity|cải thiện năng suất|B2',
  'increase revenue|tăng doanh thu|B1','reduce waste|giảm lãng phí|B1','reduce costs|giảm chi phí|B1','save time|tiết kiệm thời gian|A2','support growth|hỗ trợ tăng trưởng|B1','take a strategic approach|áp dụng cách tiếp cận chiến lược|B2','create business value|tạo giá trị kinh doanh|B2'
]));

export function expandedSuggestionItems(){return EXPANDED_SUGGESTIONS.slice();}
