import {DOMAIN_KEY,DEFAULT_DOMAINS,normalizeDomains,addDomain,renameDomain,removeDomain} from './domains-core.mjs';
const ROW_KEY='english-collocations-preview-v2';
function loadRows(){try{const v=JSON.parse(localStorage.getItem(ROW_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function saveRows(rows){if(window.PreviewTable&&window.PreviewTable.setRows)window.PreviewTable.setRows(rows);else{localStorage.setItem(ROW_KEY,JSON.stringify(rows));window.dispatchEvent(new CustomEvent('preview-data-updated'))}}
function loadDomains(){try{const v=JSON.parse(localStorage.getItem(DOMAIN_KEY)||'null');return normalizeDomains(v,null)}catch{return DEFAULT_DOMAINS.slice()}}
function saveDomains(domains){const list=normalizeDomains(domains,null);localStorage.setItem(DOMAIN_KEY,JSON.stringify(list));window.dispatchEvent(new CustomEvent('preview-domains-updated'));return list}
function ensureStored(){const current=loadDomains();if(!current.length){saveDomains(DEFAULT_DOMAINS);return DEFAULT_DOMAINS.slice()}return current}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
let modal=null;
function styles(){if(document.getElementById('domainsStyles'))return;const s=document.createElement('style');s.id='domainsStyles';s.textContent='.domain-manager{position:fixed;inset:0;background:#08101ddd;z-index:100010;display:grid;place-items:center;padding:16px}.domain-manager[hidden]{display:none}.domain-panel{width:min(520px,100%);max-height:88vh;overflow:auto;background:var(--card);border:1px solid var(--line);border-radius:15px;box-shadow:0 24px 80px #0009}.domain-head{display:flex;justify-content:space-between;align-items:center;padding:12px 14px;border-bottom:1px solid var(--line)}.domain-body{padding:12px}.domain-add{display:grid;grid-template-columns:1fr auto;gap:7px;margin-bottom:9px}.domain-add input{min-width:0}.domain-list{display:grid;gap:5px}.domain-item{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:6px;align-items:center;padding:7px 8px;border:1px solid var(--line);border-radius:9px;background:var(--card2)}.domain-name{font-size:10px;font-weight:750;word-break:break-word}.domain-item button{padding:5px 7px;font-size:9px}.domain-hint{font-size:9px;color:var(--muted);margin-bottom:7px;line-height:1.4}@media(max-width:520px){.domain-item{grid-template-columns:1fr auto auto}}';document.head.appendChild(s)}
function close(){modal?.remove();modal=null}
function propagateRename(from,to){const rows=loadRows(),next=rows.map(r=>{const domains=Array.isArray(r.domains)?r.domains.map(x=>x===from?to:x):[];const tags=Array.isArray(r.tags)?r.tags.map(x=>x===from?to:x):r.tags;return Object.assign({},r,{domains:[...new Set(domains)],tags:Array.isArray(tags)?[...new Set(tags)]:tags})});saveRows(next)}
function propagateDelete(name){const rows=loadRows(),next=rows.map(r=>Object.assign({},r,{domains:Array.isArray(r.domains)?r.domains.filter(x=>x!==name):[],tags:Array.isArray(r.tags)?r.tags.filter(x=>x!==name):r.tags}));saveRows(next)}
function open(){styles();close();modal=document.createElement('div');modal.className='domain-manager';modal.innerHTML='<div class="domain-panel" role="dialog" aria-modal="true" aria-labelledby="domainManagerTitle"><div class="domain-head"><b id="domainManagerTitle">🏷 Quản lý Domain</b><button type="button" class="secondary" id="domainClose">Đóng</button></div><div class="domain-body"><div class="domain-hint">Thêm, đổi tên hoặc xoá domain. Khi đổi tên/xoá, các row đang dùng domain sẽ được cập nhật theo.</div><div class="domain-add"><input id="domainNew" maxlength="60" placeholder="Tên domain mới…"><button type="button" id="domainAdd">＋ Thêm</button></div><div class="domain-list" id="domainList"></div></div></div>';document.body.appendChild(modal);modal.querySelector('#domainClose').onclick=close;modal.querySelector('#domainAdd').onclick=()=>{const input=modal.querySelector('#domainNew'),result=addDomain(ensureStored(),input.value);if(!result.added){input.focus();return}saveDomains(result.domains);input.value='';render()};modal.querySelector('#domainNew').onkeydown=e=>{if(e.key==='Enter')modal.querySelector('#domainAdd').click();if(e.key==='Escape')close()};modal.onclick=e=>{if(e.target===modal)close()};render()}
function render(){const list=modal?.querySelector('#domainList');if(!list)return;list.innerHTML='';for(const name of ensureStored()){const item=document.createElement('div');item.className='domain-item';const label=document.createElement('div');label.className='domain-name';label.textContent=name;const edit=document.createElement('button');edit.type='button';edit.className='secondary';edit.textContent='✎ Sửa';edit.onclick=()=>{const nextName=prompt('Đổi tên domain:',name);if(nextName===null)return;const result=renameDomain(ensureStored(),name,nextName);if(!result.changed){alert(result.duplicate?'Tên domain đã tồn tại.':'Tên domain không hợp lệ.');return}saveDomains(result.domains);propagateRename(name,result.to);render()};const del=document.createElement('button');del.type='button';del.className='danger';del.textContent='×';del.title='Xoá domain';del.onclick=()=>{if(ensureStored().length<=1)return;if(!confirm('Xoá domain “'+name+'”? Domain này sẽ được gỡ khỏi các row đang dùng nó.'))return;saveDomains(removeDomain(ensureStored(),name).domains);propagateDelete(name);render()};item.append(label,edit,del);list.appendChild(item)}}
document.addEventListener('click',e=>{if(e.target.closest?.('#domainManagerBtn')){e.preventDefault();open()}});
window.addEventListener('preview-domains-updated',()=>{const filter=document.getElementById('domainFilter');if(filter&&modal)render()});
window.PreviewDomains={getDomains:ensureStored,getSnapshot:ensureStored,restoreSnapshot(value){saveDomains(normalizeDomains(value,null));},open,refresh:()=>window.dispatchEvent(new CustomEvent('preview-domains-updated'))};
