import {familyFor} from './family-core.mjs';
import {aiJson} from './ai-client.js';
let modal=null,request=0;
const rows=()=>window.PreviewTable?.getRows?.()||[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function parse(text){try{const m=String(text||'').match(/\[[\s\S]*\]/),v=JSON.parse(m?m[0]:text);return Array.isArray(v)?v:[]}catch{return[]}}
function aiFamily(phrase){return aiJson([{role:'system',content:'Return only a JSON array of 10 common natural workplace collocations related to the supplied word. Each item must have collocation, meaningVi, type, cefr. Avoid rare, awkward or invented phrases.'},{role:'user',content:phrase}])}
function timeout(ms){return new Promise((_,reject)=>setTimeout(()=>reject(new Error('timeout')),ms))}
function add(item,base){const phrase=String(item.collocation||'').trim();if(!phrase)return false;const exists=rows().some(r=>String(r.c||'').trim().toLowerCase()===phrase.toLowerCase());if(exists)return false;const next={id:Date.now()+Math.random(),c:phrase,m:String(item.meaningVi||''),t:base.t||'',e:'',em:'',s:'Chưa học',cefr:['A1','A2','B1','B2','C1','C2'].includes(item.cefr)?item.cefr:'',domains:Array.isArray(base.domains)?base.domains:[],source:{type:'ai'},createdAt:new Date().toISOString()};window.PreviewTable?.setRows?.([...rows(),next]);return true}
async function openById(id){const row=rows().find(r=>String(r.id)===String(id));if(row)await open(row)}
async function open(row){request++;const token=request;modal?.remove();const m=document.createElement('div');modal=m;m.className='family-modal';m.innerHTML='<div class="family-panel" role="dialog" aria-modal="true" aria-labelledby="familyTitle"><div class="family-head"><div><b id="familyTitle">🌳 Collocation Family</b><div class="family-sub">'+esc(row.c)+'</div></div><button type="button" class="secondary" id="familyClose">Đóng</button></div><div id="familyBody"><div class="family-loading">🧠 Đang xây family…</div></div></div>';document.body.appendChild(m);m.querySelector('#familyClose').onclick=()=>{request++;m.remove();modal=null};m.onclick=e=>{if(e.target===m){request++;m.remove();modal=null}};let items=familyFor(row.c);if(!items.length){try{const raw=await Promise.race([aiFamily(row.c),timeout(15000)]);if(token!==request)return;items=parse(raw).map(x=>({collocation:String(x?.collocation||'').trim(),meaningVi:String(x?.meaningVi||''),type:String(x?.type||'Collocation'),cefr:['A1','A2','B1','B2','C1','C2'].includes(String(x?.cefr||''))?String(x.cefr):''})).filter(x=>x.collocation).slice(0,10)}catch{if(token!==request)return;const body=m.querySelector('#familyBody');body.innerHTML='<div class="family-error">⚠️ Chưa lấy được Collocation Family. Kiểm tra AI rồi thử lại.</div><button type="button" class="secondary" id="familyRetry" style="margin:10px 14px">↻ Thử lại</button>';body.querySelector('#familyRetry').onclick=()=>open(row);return}}
if(token!==request)return;const body=m.querySelector('#familyBody');body.innerHTML='';if(!items.length){body.innerHTML='<div class="family-error" style="padding:14px">Chưa có family cho cụm này.</div>';return}for(const item of items){const box=document.createElement('div');box.className='family-item';const info=document.createElement('div');const b=document.createElement('b');b.textContent=item.collocation;const meta=document.createElement('span');meta.textContent=item.type+(item.cefr?' · '+item.cefr:'');const v=document.createElement('small');v.textContent=item.meaningVi;info.append(b,meta,v);const btn=document.createElement('button');btn.type='button';btn.className='secondary';btn.textContent='＋ Thêm';btn.onclick=()=>{const ok=add(item,row);btn.textContent=ok?'✓ Đã thêm':'Đã có';btn.disabled=true};box.append(info,btn);body.appendChild(box)}}
function boot(){if(document.getElementById('familyStyles'))return;const s=document.createElement('style');s.id='familyStyles';s.textContent='.family-modal{position:fixed;inset:0;background:#08101ddd;z-index:100006;display:grid;place-items:center;padding:16px}.family-panel{width:min(650px,100%);max-height:88vh;overflow:auto;background:var(--card);border:1px solid var(--line);border-radius:15px;box-shadow:0 22px 70px #0008}.family-head{display:flex;justify-content:space-between;gap:10px;padding:12px 14px;border-bottom:1px solid var(--line)}.family-sub{font-size:9px;color:var(--muted);margin-top:2px}.family-loading,.family-error{font-size:10px;color:var(--muted);padding:14px}.family-item{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px 14px;border-bottom:1px solid var(--line)}.family-item b{display:block;font-size:10px}.family-item span{display:block;color:var(--blue);font-size:8px;margin-top:2px}.family-item small{display:block;color:var(--muted);font-size:9px;margin-top:2px}.family-item button{font-size:9px;white-space:nowrap}';document.head.appendChild(s);document.addEventListener('click',e=>{const f=e.target.closest?.('[data-family]');if(f){e.preventDefault();e.stopPropagation();openById(f.dataset.family)}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
window.PreviewFamily={openById,open};
