import {familyFor} from './family-core.mjs';import {aiJson} from './ai-client.js';
let modal=null;
const rows=()=>window.PreviewTable?.getRows?.()||[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function aiFamily(phrase){return aiJson([{role:'system',content:'Return only a JSON array of 5 common natural workplace collocations related to the supplied word. Each item: collocation, meaningVi, type, cefr. Avoid rare or invented phrases.'},{role:'user',content:phrase}])}
function parse(t){try{const m=String(t||'').match(/\[[\s\S]*\]/),v=JSON.parse(m?m[0]:t);return Array.isArray(v)?v:[]}catch{return[]}}
function add(item,base){const phrase=String(item.collocation||'').trim();if(!phrase)return;const exists=rows().some(r=>String(r.c||'').trim().toLowerCase()===phrase.toLowerCase());if(exists)return;const next={id:Date.now()+Math.random(),c:phrase,m:String(item.meaningVi||''),t:base.t||'',e:'',em:'',s:'Chưa học',cefr:['A1','A2','B1','B2','C1','C2'].includes(item.cefr)?item.cefr:'B1',domains:Array.isArray(base.domains)?base.domains:[],source:{type:'ai'},createdAt:new Date().toISOString()};window.PreviewTable?.setRows?.([...rows(),next])}
async function open(row){modal?.remove();const m=document.createElement('div');modal=m;m.className='family-modal';m.innerHTML='<div class="family-panel" role="dialog" aria-modal="true"><div class="family-head"><div><b>🌳 Collocation Family</b><div class="family-sub">'+esc(row.c)+'</div></div><button type="button" class="secondary" id="familyClose">Đóng</button></div><div id="familyBody"><div class="family-loading">Đang xây family…</div></div></div>';document.body.appendChild(m);m.querySelector('#familyClose').onclick=()=>m.remove();let items=familyFor(row.c);if(!items.length){try{items=parse(await aiFamily(row.c)).map(x=>({collocation:String(x.collocation||''),meaningVi:String(x.meaningVi||''),type:String(x.type||'Collocation'),cefr:String(x.cefr||'B1')})).filter(x=>x.collocation).slice(0,8)}catch{items=[]}}const body=m.querySelector('#familyBody');body.innerHTML='';if(!items.length){body.textContent='Chưa có family cho từ này.';return}items.forEach(item=>{const box=document.createElement('div');box.className='family-item';const info=document.createElement('div');const b=document.createElement('b');b.textContent=item.collocation;const t=document.createElement('span');t.textContent=item.type+' · '+item.cefr;const v=document.createElement('small');v.textContent=item.meaningVi;info.append(b,t,v);const btn=document.createElement('button');btn.type='button';btn.className='secondary';btn.textContent='＋ Thêm';btn.onclick=()=>{add(item,row);btn.textContent='✓ Đã thêm';btn.disabled=true};box.append(info,btn);body.appendChild(box)})}
function boot(){const s=document.createElement('style');s.id='familyStyles';s.textContent='.family-modal{position:fixed;inset:0;background:#08101ddd;z-index:100006;display:grid;place-items:center;padding:16px}.family-panel{width:min(650px,100%);max-height:88vh;overflow:auto;background:var(--card);border:1px solid var(--line);border-radius:17px}.family-head{display:flex;justify-content:space-between;gap:10px;padding:13px 15px;border-bottom:1px solid var(--line)}.family-sub,.family-loading{font-size:10px;color:var(--muted);margin-top:2px}.family-item{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 14px;border-bottom:1px solid var(--line)}.family-item b{display:block;font-size:11px}.family-item span{display:block;color:var(--blue);font-size:8px;margin-top:2px}.family-item small{display:block;color:var(--muted);font-size:9px;margin-top:2px}.family-item button{font-size:9px;white-space:nowrap}';document.head.appendChild(s);document.addEventListener('click',e=>{const tr=e.target.closest?.('#body tr[data-id]');if(!tr||e.target.closest('button,input,.editable'))return;const row=rows().find(r=>String(r.id)===String(tr.dataset.id));if(row)open(row)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();window.PreviewFamily={open};
