import {GOALS_KEY,GOAL_PERIODS,DEFAULT_GOALS,normalizeTarget,normalizeGoals,countLearned,progressModel,periodLabel} from './goals-core.mjs';
import {ANALYTICS_KEY,localDateKey} from './analytics-core.mjs';

function load(){try{return normalizeGoals(JSON.parse(localStorage.getItem(GOALS_KEY)||'null'))}catch{return {...DEFAULT_GOALS}}}
function save(value){localStorage.setItem(GOALS_KEY,JSON.stringify(normalizeGoals(value)));window.dispatchEvent(new CustomEvent('preview-goals-updated'))}
function loadEvents(){try{const v=JSON.parse(localStorage.getItem(ANALYTICS_KEY)||'null');return Array.isArray(v?.learningEvents)?v.learningEvents:[]}catch{return []}}

function styles(){if(document.getElementById('goalsStyles'))return;const s=document.createElement('style');s.id='goalsStyles';s.textContent=`.goals-card{padding:12px}.feature-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.feature-title{font-size:16px;font-weight:850}.feature-sub{font-size:10px;color:var(--muted);margin-top:2px}.goal-list{display:grid;gap:8px;margin-top:10px}.goal-row{padding:8px 9px;border:1px solid var(--line);border-radius:10px;background:var(--card2)}.goal-row-head{display:flex;align-items:center;justify-content:space-between;gap:8px;font-size:10px}.goal-label{font-weight:800}.goal-target{display:flex;align-items:center;gap:4px}.goal-target input{width:66px;padding:5px 6px;font-size:10px;text-align:right}.goal-count{color:var(--muted);font-size:9px}.goal-progress{height:8px;border-radius:999px;background:var(--line);overflow:hidden;margin-top:7px}.goal-progress>i{display:block;height:100%;border-radius:999px;background:var(--blue);transition:width .25s ease}.goal-progress>i.complete{background:var(--green)}.goal-foot{font-size:9px;color:var(--muted);margin-top:6px}`;document.head.appendChild(s)}
function ensureCard(){if(document.getElementById('goalsCard'))return document.getElementById('goalsCard');const anchor=document.querySelector('.analytics-card'),card=document.createElement('section');card.id='goalsCard';card.className='card goals-card';card.innerHTML='<div class="feature-head"><div><div class="feature-title">🎯 Mục tiêu học</div><div class="feature-sub">Đặt mục tiêu collocation Đã học theo ngày, tuần, tháng và năm.</div></div></div><div class="goal-list" id="goalList"></div><div class="goal-foot">Tiến độ tính theo số collocation duy nhất đã học trong từng khoảng thời gian.</div>';if(anchor)anchor.insertAdjacentElement('afterend',card);else document.querySelector('.sidebar')?.prepend(card);return card}
function refresh(){styles();const card=ensureCard(),list=card.querySelector('#goalList'),goals=load(),events=loadEvents(),now=new Date();list.innerHTML='';for(const period of GOAL_PERIODS){const model=progressModel(goals[period],countLearned(events,period,now));const row=document.createElement('div');row.className='goal-row';row.innerHTML='<div class="goal-row-head"><span class="goal-label">'+periodLabel(period)+'</span><span class="goal-target"><input type="number" min="0" max="100000" step="1" data-goal="'+period+'" value="'+model.target+'" aria-label="Mục tiêu '+periodLabel(period)+'"><span class="goal-count">'+model.actual+'/'+model.target+'</span></span></div><div class="goal-progress" role="progressbar" aria-valuemin="0" aria-valuemax="'+model.target+'" aria-valuenow="'+Math.min(model.actual,model.target)+'" aria-label="Tiến độ '+periodLabel(period)+'"><i class="'+(model.complete?'complete':'')+'" style="width:'+model.percent+'%"></i></div>';list.appendChild(row)}list.querySelectorAll('input[data-goal]').forEach(input=>input.addEventListener('change',()=>{const next=load();next[input.dataset.goal]=normalizeTarget(input.value,0);save(next);refresh()}))}
window.PreviewGoals={getSnapshot:load,restoreSnapshot(value){save(normalizeGoals(value));refresh()},refresh};
window.addEventListener('preview-data-updated',refresh);
window.addEventListener('storage',e=>{if(e.key===GOALS_KEY||e.key===ANALYTICS_KEY)refresh()});
refresh();
