import {GOALS_KEY,GOAL_PERIODS,normalizeTarget,normalizeGoals,countLearned,progressModel,periodLabel,deriveGoalTargets} from './goals-core.mjs';
import {ANALYTICS_KEY} from './analytics-core.mjs';
function load(){try{return normalizeGoals(JSON.parse(localStorage.getItem(GOALS_KEY)||'null'),new Date())}catch{return normalizeGoals({},new Date())}}
function save(value){localStorage.setItem(GOALS_KEY,JSON.stringify(normalizeGoals(value,new Date())));window.dispatchEvent(new CustomEvent('preview-goals-updated'))}
function loadEvents(){try{const v=JSON.parse(localStorage.getItem(ANALYTICS_KEY)||'null');return Array.isArray(v?.learningEvents)?v.learningEvents:[]}catch{return []}}
function styles(){if(document.getElementById('goalsStyles'))return;const s=document.createElement('style');s.id='goalsStyles';s.textContent='.goals-card{padding:12px}.goal-list{display:grid;gap:7px;margin-top:9px}.goal-row{padding:8px 9px;border:1px solid var(--line);border-radius:10px;background:var(--card2)}.goal-row-head{display:flex;align-items:center;justify-content:space-between;gap:8px;font-size:10px}.goal-label{font-weight:850}.goal-target{display:flex;align-items:center;gap:4px}.goal-target input{width:64px;padding:5px 6px;font-size:10px;text-align:right}.goal-target input[readonly]{opacity:.7}.goal-count{color:var(--muted);font-size:9px}.goal-progress{height:7px;border-radius:999px;background:var(--line);overflow:hidden;margin-top:6px}.goal-progress>i{display:block;height:100%;border-radius:999px;background:var(--blue);transition:width .2s ease}.goal-progress>i.complete{background:var(--green)}.goal-foot{font-size:9px;color:var(--muted);margin-top:6px;line-height:1.4}.goal-base-note{font-size:9px;color:var(--blue);margin-top:4px}';document.head.appendChild(s)}
function ensureCard(){if(document.getElementById('goalsCard'))return document.getElementById('goalsCard');const anchor=document.querySelector('.analytics-card'),card=document.createElement('section');card.id='goalsCard';card.className='card goals-card';card.innerHTML='<div class="feature-head"><div><div class="feature-title">🎯 Mục tiêu học</div><div class="feature-sub">Ngày là mục tiêu gốc; tuần, tháng và năm tự cộng dồn.</div></div></div><div class="goal-list" id="goalList"></div><div class="goal-foot">Thiết lập 1 con số/ngày. Các mốc dài hơn tự tính theo lịch Việt Nam.</div>';if(anchor)anchor.insertAdjacentElement('afterend',card);else document.querySelector('.sidebar')?.prepend(card);return card}
function refresh(){styles();const card=ensureCard(),list=card.querySelector('#goalList'),goals=load(),events=loadEvents(),now=new Date(),targets=deriveGoalTargets(goals.day,now);list.innerHTML='';for(const period of GOAL_PERIODS){const model=progressModel(targets[period],countLearned(events,period,now)),editable=period==='day';const row=document.createElement('div');row.className='goal-row';row.innerHTML='<div class="goal-row-head"><span class="goal-label">'+periodLabel(period)+'</span><span class="goal-target"><input type="number" min="0" max="100000" step="1" data-goal="'+period+'" value="'+model.target+'" '+(editable?'':'readonly')+' aria-label="Mục tiêu '+periodLabel(period)+'"><span class="goal-count">'+model.actual+'/'+model.target+'</span></span></div><div class="goal-progress" role="progressbar" aria-valuemin="0" aria-valuemax="'+model.target+'" aria-valuenow="'+Math.min(model.actual,model.target)+'" aria-label="Tiến độ '+periodLabel(period)+'"><i class="'+(model.complete?'complete':'')+'" style="width:'+model.percent+'%"></i></div>'+(!editable?'<div class="goal-base-note">↳ '+targets.day+' cụm/ngày</div>':'');list.appendChild(row)}list.querySelector('[data-goal="day"]')?.addEventListener('change',e=>{const next={...load(),day:normalizeTarget(e.target.value,0)};save(next);refresh()})}
window.PreviewGoals={getSnapshot:load,restoreSnapshot(value){save(normalizeGoals(value,new Date()));refresh()},refresh};
window.addEventListener('preview-data-updated',e=>{const kind=e.detail?.kind;if(kind==='status'||kind==='collection'||kind==='restore')refresh()});window.addEventListener('storage',e=>{if(e.key===GOALS_KEY||e.key===ANALYTICS_KEY)refresh()});refresh();
