export const GRAMMAR_KEY='english-collocations-preview-grammar-v1';

export const GRAMMAR_TOPICS=[
{id:'sentence-foundations',level:'Foundation',category:'Cấu trúc câu',title:'S / V / O / C / A',summary:'Nắm khung câu cơ bản để đọc và tự đặt câu đúng.',formula:'S + V + O / S + be + C / S + V + A',examples:['I design products.','She is responsible for the project.','We work from home.'],notes:['S = Subject (chủ ngữ)','V = Verb (động từ)','O = Object (tân ngữ)','C = Complement (bổ ngữ)','A = Adverbial (trạng ngữ)'],common:'Nhầm Complement với Object hoặc đặt trạng ngữ sai vị trí.'},
{id:'word-classes',level:'Foundation',category:'Nền tảng',title:'Từ loại',summary:'Phân biệt noun, verb, adjective, adverb và cách chúng đứng trong câu.',formula:'Noun → người/vật/ý tưởng · Verb → hành động/trạng thái · Adj → mô tả · Adv → bổ nghĩa',examples:['The new feature works well.','Clear communication matters.','We communicate clearly.'],notes:['Danh từ thường làm S/O/C','Tính từ thường bổ nghĩa N hoặc đứng sau linking verb','Trạng từ thường bổ nghĩa V/Adj/Adv/cả mệnh đề'],common:'Chọn sai từ loại khi biến đổi từ.'},
{id:'nouns-plurals',level:'Foundation',category:'Nền tảng',title:'Danh từ & số nhiều',summary:'Nắm singular/plural, countable/uncountable và lượng từ.',formula:'a/an + singular countable · many/few + plural · much/little + uncountable',examples:['We need more information.','She has three tasks.','There is a solution.'],notes:['information, advice, equipment thường không đếm được','people, children có dạng số nhiều bất quy tắc'],common:'Dùng informations, advices hoặc much với danh từ đếm được.'},
{id:'articles',level:'Foundation',category:'Nền tảng',title:'A / An / The / Ø',summary:'Dùng mạo từ để nói về một đối tượng chưa xác định, đã xác định hoặc nói chung.',formula:'a/an = một đối tượng bất kỳ · the = đã xác định · Ø = nói chung',examples:['I need a designer.','The designer joined the meeting.','Design is important.'],notes:['a/an chỉ dùng với singular countable noun','the dùng khi người nghe có thể xác định đối tượng'],common:'Bỏ the khi danh từ đã được xác định hoặc thêm the trước khái niệm chung.'},
{id:'be-do-have',level:'Foundation',category:'Trợ động từ',title:'Be / Do / Have',summary:'Hiểu vai trò của be, do, have trong câu và câu hỏi.',formula:'be + Adj/N/PP · do + V nguyên mẫu · have + V3 hoặc sở hữu',examples:['Are you ready?','Do you work remotely?','Have you finished?'],notes:['be có thể là main verb','do hỗ trợ câu hỏi/phủ định ở simple tenses','have dùng trong perfect hoặc nghĩa sở hữu'],common:'Dùng do với be hoặc quên trợ động từ trong câu hỏi.'},
{id:'questions',level:'Foundation',category:'Câu hỏi',title:'Câu hỏi Yes/No & Wh-',summary:'Tạo câu hỏi đúng trật tự và chọn đúng từ hỏi.',formula:'Aux + S + V...? · Wh-word + Aux + S + V...?',examples:['Do you work in banking?','Where do you live?','Are you working today?'],notes:['Who/What có thể là subject nên không cần do trong một số câu hỏi','Sau do/does/did dùng V nguyên mẫu'],common:'Giữ nguyên V-s sau does hoặc sai thứ tự Wh + auxiliary + subject.'},
{id:'present-simple',level:'Foundation',category:'Thì',title:'Present Simple',summary:'Thói quen, sự thật, lịch trình và trạng thái ổn định.',formula:'S + V(s/es) · do/does + not + V',examples:['I work with product teams.','She designs mobile apps.','The meeting starts at 9.'],notes:['He/She/It + V-s/es','Dùng do/does trong phủ định và câu hỏi'],common:'Quên -s với ngôi thứ ba số ít.'},
{id:'present-continuous',level:'Foundation',category:'Thì',title:'Present Continuous',summary:'Hành động đang diễn ra hoặc tình huống tạm thời.',formula:'S + am/is/are + V-ing',examples:['I am working on a new flow.','They are testing the prototype.'],notes:['be + V-ing là dấu hiệu cốt lõi','Có thể dùng cho kế hoạch gần trong tương lai'],common:'Quên be hoặc dùng V-ing sau do/does.'},
{id:'past-simple',level:'Foundation',category:'Thì',title:'Past Simple',summary:'Sự việc đã xảy ra và kết thúc trong quá khứ.',formula:'S + V2/ed · did + not + V',examples:['We launched the feature last week.','I joined the meeting yesterday.'],notes:['Dùng mốc thời gian quá khứ rõ','Sau did dùng V nguyên mẫu'],common:'Dùng V2 sau did hoặc trộn với present perfect.'},
{id:'present-perfect',level:'Intermediate',category:'Thì',title:'Present Perfect',summary:'Kinh nghiệm, kết quả hiện tại hoặc hành động kéo dài đến hiện tại.',formula:'S + have/has + V3',examples:['I have completed the research.','We have worked together for two years.'],notes:['for + khoảng thời gian','since + mốc bắt đầu','just/already/yet thường gặp'],common:'Dùng với mốc quá khứ đã kết thúc như yesterday.'},
{id:'future',level:'Intermediate',category:'Thì',title:'Will / Be going to / Present Continuous',summary:'Phân biệt quyết định tức thời, dự định và kế hoạch đã sắp xếp.',formula:'will + V · be going to + V · be + V-ing',examples:['I will call you back.','We are going to improve onboarding.','We are meeting the client tomorrow.'],notes:['will: decision/prediction','going to: intention/evidence','present continuous: arrangement'],common:'Dùng một công thức cho mọi loại tương lai.'},
{id:'modals',level:'Intermediate',category:'Động từ khuyết thiếu',title:'Modal Verbs',summary:'Diễn đạt khả năng, nghĩa vụ, lời khuyên, sự cho phép và mức độ chắc chắn.',formula:'modal + V nguyên mẫu',examples:['We should test this first.','You must follow the policy.','It might work.'],notes:['can/could: ability/possibility','should: advice','must/have to: obligation','might/may: possibility'],common:'Thêm -s hoặc to sau modal.'},
{id:'passive',level:'Intermediate',category:'Câu bị động',title:'Passive Voice',summary:'Tập trung vào hành động/kết quả thay vì người thực hiện.',formula:'be + V3',examples:['The report was approved.','The data is stored securely.'],notes:['Giữ đúng tense của be','by + agent chỉ cần khi agent quan trọng'],common:'Dùng sai dạng be hoặc quên V3.'},
{id:'gerund-infinitive',level:'Intermediate',category:'Verb patterns',title:'Gerund & Infinitive',summary:'Biết động từ nào đi với V-ing và động từ nào đi với to-V.',formula:'verb + V-ing / verb + to-V / verb + object + to-V',examples:['I enjoy learning English.','We need to improve the flow.','She asked me to review it.'],notes:['enjoy, avoid, consider + V-ing','want, need, decide + to-V','ask/tell/allow + object + to-V'],common:'Dùng V-ing sau mọi động từ.'},
{id:'comparatives',level:'Intermediate',category:'So sánh',title:'Comparatives & Superlatives',summary:'So sánh hơn, nhất và bằng để mô tả sản phẩm, dữ liệu và kết quả.',formula:'adj-er / more + adj · the adj-est / the most + adj',examples:['This flow is simpler.','The new version is more efficient.','This is the most useful insight.'],notes:['short adjective → -er/-est','long adjective → more/most','as + adj + as = bằng'],common:'Dùng more với tính từ ngắn hoặc quên the ở superlative.'},
{id:'prepositions-time-place',level:'Intermediate',category:'Giới từ',title:'Prepositions: Time & Place',summary:'Phân biệt in/on/at và các giới từ vị trí thường dùng.',formula:'at + point · on + day/surface · in + period/area',examples:['at 9 a.m.','on Monday','in Vietnam','on the screen'],notes:['at the office / at work','in a room / in a city','on the page / on the table'],common:'Dịch từng từ từ tiếng Việt sang tiếng Anh.'},
{id:'relative-clauses',level:'Upper-Intermediate',category:'Mệnh đề',title:'Relative Clauses',summary:'Gộp thông tin về người/vật bằng who, which, that, where, whose.',formula:'N + who/which/that + clause',examples:['The user who reported the issue replied.','The flow that we designed is simpler.'],notes:['who → people','which → things','that → people/things trong defining clause'],common:'Lặp subject hoặc dùng sai relative pronoun.'},
{id:'conditionals',level:'Upper-Intermediate',category:'Mệnh đề',title:'Conditionals 0–3',summary:'Diễn đạt điều kiện thực tế, khả năng, giả định hiện tại và quá khứ.',formula:'0: if + present, present · 1: if + present, will + V · 2: if + past, would + V · 3: if + had V3, would have V3',examples:['If users struggle, we redesign the flow.','If we test early, we will save time.','If I had more time, I would research more.'],notes:['Type 0 = fact/routine','Type 1 = real possibility','Type 2 = unreal/less likely','Type 3 = past unreal'],common:'Trộn tense giữa các type.'},
{id:'reported-speech',level:'Upper-Intermediate',category:'Mệnh đề',title:'Reported Speech',summary:'Tường thuật lại lời nói, câu hỏi và yêu cầu.',formula:'say/tell + clause · ask + if/wh · tell + object + to-V',examples:['She said that the issue was fixed.','He asked whether we needed help.'],notes:['Lùi thì khi ngữ cảnh yêu cầu','Đổi đại từ và trạng từ thời gian theo context'],common:'Giữ nguyên toàn bộ câu trực tiếp mà không đổi context.'},
{id:'discourse-linkers',level:'Upper-Intermediate',category:'Liên kết ý',title:'Linking Words & Discourse Markers',summary:'Nối ý tự nhiên khi trình bày, họp và viết email.',formula:'however · therefore · although · whereas · in addition · as a result',examples:['However, the data is still limited.','Therefore, we should run another test.'],notes:['however = contrast','therefore = result','although = concession','whereas = contrast between two things'],common:'Dùng quá nhiều and/but nên câu thiếu logic.'},
{id:'advanced-emphasis',level:'Advanced',category:'Nâng cao',title:'Emphasis & Inversion',summary:'Tạo câu nhấn mạnh để nói và viết chuyên nghiệp hơn.',formula:'It is/was X that... · Not only... but also... · Rarely + auxiliary + S...',examples:['It was the onboarding flow that caused the drop.','Not only did we improve speed, but we also reduced errors.'],notes:['Dùng có chủ đích trong formal/professional English','Inversion cần auxiliary trước subject'],common:'Dùng cấu trúc nhấn mạnh quá dày hoặc sai auxiliary.'},
{id:'advanced-participles',level:'Advanced',category:'Nâng cao',title:'Participle Clauses',summary:'Rút gọn mệnh đề để câu gọn và tự nhiên hơn trong văn viết.',formula:'V-ing..., V3/ed..., Having + V3...',examples:['Having reviewed the data, we changed the flow.','Designed for mobile users, the page loads quickly.'],notes:['V-ing thường cùng chủ thể với mệnh đề chính','Having + V3 = hành động xảy ra trước'],common:'Dangling participle: chủ thể ngầm không khớp.'},
];

export function grammarLevels(){return ['All','Foundation','Intermediate','Upper-Intermediate','Advanced']}
export function grammarCategories(){return ['All',...new Set(GRAMMAR_TOPICS.map(x=>x.category))]}
export function loadGrammarProgress(){try{const v=JSON.parse(localStorage.getItem(GRAMMAR_KEY)||'{}');return v&&typeof v==='object'?v:{}}catch{return {}}}
export function saveGrammarProgress(value){localStorage.setItem(GRAMMAR_KEY,JSON.stringify(value||{}))}
export function toggleGrammarDone(progress,id){const next={...(progress||{})};next[id]={done:!next[id]?.done,updatedAt:new Date().toISOString()};saveGrammarProgress(next);return next}
export function getGrammarStats(progress){const done=GRAMMAR_TOPICS.filter(x=>progress?.[x.id]?.done).length;return{total:GRAMMAR_TOPICS.length,done,remaining:GRAMMAR_TOPICS.length-done,percent:GRAMMAR_TOPICS.length?Math.round(done/GRAMMAR_TOPICS.length*100):0}}
