import {fastSuggestions,ruleRefinement,refinementPrompt} from './smart-tools-core.mjs';
const DATA_KEY='english-collocations-preview-v2';
const MODEL='onnx-community/Qwen2.5-0.5B-Instruct';
let timer=0,worker=null,requestId=0,activeRequest=0,busy=false;
const esc=value=>String(value??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function readRows(){try{const v=JSON.parse(localStorage.getItem(DATA_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return []}}
function selectedRows(){const ids=[...document.querySelectorAll('#body .row-check:checked')].map(el=>String(el.closest('tr')?.dataset.id||''));const rows=readRows();return ids.length?rows.filter(r=>ids.includes(String(r.id))):[]}
function getWorker(){if(!worker)worker=new Worker('./ai-agent-worker.js?v=8',{type:'module'});return worker}
function aiJson(messages){return new Promise((resolve,reject)=>{const id=++requestId,w=getWorker();const fn=e=>{if(e.data?.id!==id)return;if(e.data?.type==='status')return;w.removeEventListener('message',fn);e.data.ok?resolve(e.data.text):reject(new Error(e.data.error||'AI unavailable'))};w.addEventListener('message',fn);w.postMessage({id,messages,batch:true})})}
function parseArray(text){try{const cleaned=String(text||'').replace(/^```(?:json|text)?\s*/i,'').replace(/\s*```$/,'').trim();const match=cleaned.match(/\[[\s\S]*\]/);const value=JSON.parse(match?match[0]:cleaned);return Array.isArray(value)?value:[]}catch{return []}}
function styles(){if(document.getElementById('smartStyles'))return;const s=document.createElement('style');s.id='smartStyles';s.textContent='.suggest-popover{position:fixed;z-index:100003;width:min(290px,calc(100vw - 20px));background:var(--card);border:1px solid var(--line);border-radius:12px;box-shadow:0 18px 50px #0008;padding:8px}.suggest-head{font-size:10px;color:var(--muted);padding:2px 3px 6px}.suggest-list{display:grid;gap:4px;max-height:220px;overflow:auto}.suggestion-btn{width:100%;text-align:left;background:var(--card2);border:1px solid var(--line);color:var(--text);border-radius:8px;padding:8px;font-size:10px;cursor:pointer}.suggestion-btn:hover{border-color:var(--blue)}.suggest-note{font-size:9px;color:var(--muted);padding:6px 3px 1px}.refine-card{padding:12px}.refine-controls{display:flex;gap:6px;margin-top:9px}.refine-run{flex:1}.refine-status{font-size:10px;color:var(--muted);margin-top:8px}.refine-list{display:grid;gap:8px;margin-top:9px}.refine-item{border:1px solid var(--line);background:var(--card2);border-radius:11px;padding:9px}.refine-top{display:flex;align-items:flex-start;justify-content:space-between;gap:8px}.refine-phrase{font-size:11px;font-weight:900;line-height:1.35}.refine-score{min-width:46px;text-align:center;padding:3px 6px;border-radius:999px;background:#183966;color:#8fb8ff;font-size:9px;font-weight:900}.refine-tags{display:flex;flex-wrap:wrap;gap:5px;margin-top:6px}.refine-tag{font-size:8px;color:var(--muted);border:1px solid var(--line);border-radius:999px;padding:3px 6px}.refine-warning{font-size:10px;line-height:1.45;margin-top:7px}.refine-better{font-size:10px;color:var(--green);margin-top:7px}.refine-actions{display:flex;justify-content:flex-end;margin-top:7px}.refine-actions button{padding:5px 7px;font-size:9px}';document.head.appendChild(s)}
function closeSuggest(){document.getElementById('suggestPopover')?.remove()}
function position(pop,cell){document.body.appendChild(pop);const r=cell.getBoundingClientRect(),w=pop.offsetWidth,h=pop.offsetHeight;pop.style.left=Math.min(Math.max(8,r.left),innerWidth-w-8)+'px';const top=r.bottom+5;pop.style.top=(top+h<=innerHeight-8?top:Math.max(8,r.top-h-5))+'px'}
function fill(cell,value){cell.textContent=value;cell.dispatchEvent(new Event('input',{bubbles:true}));cell.blur();closeSuggest()}
function showSuggestions(cell,values,label){closeSuggest();if(!values.length)return;const pop=document.createElement('div');pop.id='suggestPopover';pop.className='suggest-popover';const head=document.createElement('div');head.className='suggest-head';head.textContent=label||'💡 Gợi ý collocation';pop.appendChild(head);const list=document.createElement('div');list.className='suggest-list';values.slice(0,5).forEach(value=>{const b=document.createElement('button');b.type='button';b.className='suggestion-btn';b.textContent=value;b.addEventListener('mousedown',e=>e.preventDefault());b.addEventListener('click',()=>fill(cell,value));list.appendChild(b)});pop.appendChild(list);const note=document.createElement('div');note.className='suggest-note';note.textContent='Bấm để fill nhanh vào cột Collocation.';pop.appendChild(note);position(pop,cell)}
function handleInput(e){const cell=e.target.closest?.('.editable[data-field="c"]');if(!cell)return;clearTimeout(timer);closeSuggest();const value=String(cell.textContent||'').trim();if(value.length<2)return;const fast=fastSuggestions(value);if(fast.length){showSuggestions(cell,fast,'⚡ Gợi ý nhanh');return}const token=++activeRequest;timer=setTimeout(async()=>{try{const raw=await aiJson([{role:'system',content:'Return only a JSON array of 3-5 common English collocations related to the supplied headword. Use workplace English. No explanations.'},{role:'user',content:value}]);if(token!==activeRequest)return;const values=parseArray(raw).map(x=>String(x||'').trim()).filter(Boolean).slice(0,5);if(values.length)showSuggestions(cell,values,'🤖 Gợi ý AI')}catch{}},600)}
function refinementCard(){if(document.getElementById('refinementCard'))return document.getElementById('refinementCard');const anchor=document.getElementById('srsCard')||document.getElementById('goalsCard')||document.querySelector('.analytics-card');const card=document.createElement('section');card.id='refinementCard';card.className='card refine-card';card.innerHTML='<div class="feature-head"><div><div class="feature-title">✨ Smart Refinement</div><div class="feature-sub">Naturalness, cảnh báo nhầm lẫn và Register/Tone.</div></div></div><div class="refine-controls"><button class="secondary refine-run" id="refineRun" type="button">🔍 Phân tích dòng đã chọn</button></div><div class="refine-status" id="refineStatus">Chọn 1–8 dòng để phân tích.</div><div class="refine-list" id="refineList"></div>';if(anchor)anchor.insertAdjacentElement('afterend',card);else document.querySelector('.sidebar')?.appendChild(card);card.querySelector('#refineRun').addEventListener('click',runRefinement);return card}
function renderRefinement(items){const card=refinementCard(),list=card.querySelector('#refineList');list.innerHTML='';if(!items.length){list.innerHTML='<div class="refine-status">Chưa có kết quả.</div>';return}for(const item of items){const el=document.createElement('div');el.className='refine-item';const better=item.better||'';el.innerHTML='<div class="refine-top"><div class="refine-phrase">'+esc(item.phrase)+'</div><div class="refine-score">'+(Number.isFinite(item.score)?item.score+'/100':'—')+'</div></div><div class="refine-tags"><span class="refine-tag">Register · '+esc(item.register||'Chưa đánh giá')+'</span><span class="refine-tag">Tone · '+esc(item.tone||'Chưa đánh giá')+'</span></div>'+(item.warning?'<div class="refine-warning">⚠️ '+esc(item.warning)+'</div>':'')+(better?'<div class="refine-better">→ Gợi ý: <b>'+esc(better)+'</b></div><div class="refine-actions"><button type="button" class="secondary" data-refine-id="'+esc(item.id)+'" data-refine-value="'+esc(better.split('/')[0].trim())+'">Fill gợi ý</button></div>':'');list.appendChild(el)}list.querySelectorAll('[data-refine-id]').forEach(btn=>btn.addEventListener('click',()=>{const cell=document.querySelector('#body tr[data-id="'+CSS.escape(btn.dataset.refineId)+'"] .editable[data-field="c"]');if(cell)fill(cell,btn.dataset.refineValue)}))}
async function runRefinement(){if(busy)return;const rows=selectedRows(),card=refinementCard(),status=card.querySelector('#refineStatus');if(!rows.length){status.textContent='⚠️ Hãy chọn ít nhất một dòng.';return}if(rows.length>8){status.textContent='⚠️ Tối đa 8 dòng mỗi lần.';return}busy=true;card.querySelector('#refineRun').disabled=true;status.textContent='🧠 AI đang phân tích theo batch…';try{const raw=await aiJson([{role:'system',content:'You are a careful English collocation editor. Return only a JSON array, one object per input row. Fields: index, naturalnessScore (0-100), betterCollocation, confusionWarning, register, tone. Register: Formal, Informal, Academic/IELTS. Tone: neutral, professional, friendly, casual. Score the exact phrase as written. Keep all explanations concise.'},{role:'user',content:refinementPrompt(rows)}]);const arr=parseArray(raw);const merged=rows.map((row,i)=>{const a=arr.find(x=>Number(x?.index)===i+1)||{},rule=ruleRefinement(row.c);return{id:String(row.id),phrase:String(row.c||''),score:Number.isFinite(Number(a.naturalnessScore))?Math.max(0,Math.min(100,Math.round(Number(a.naturalnessScore)))):null,better:rule?.better||String(a.betterCollocation||'').trim(),warning:rule?.message||String(a.confusionWarning||'').trim(),register:String(a.register||'Chưa đánh giá'),tone:String(a.tone||'Chưa đánh giá')}});renderRefinement(merged);status.textContent='✓ Phân tích xong · chưa sửa dữ liệu'}catch(error){renderRefinement(rows.map(row=>{const rule=ruleRefinement(row.c);return{id:String(row.id),phrase:String(row.c||''),score:null,better:rule?.better||'',warning:rule?.message||'Chưa có cảnh báo rule-based cho cụm này.',register:'Chưa đánh giá',tone:'Chưa đánh giá'}}));status.textContent='⚠️ AI chưa sẵn sàng.'}finally{busy=false;card.querySelector('#refineRun').disabled=false}}
styles();refinementCard();document.addEventListener('input',handleInput);document.addEventListener('focusin',e=>{if(!e.target.closest?.('.editable[data-field="c"]'))closeSuggest()});document.addEventListener('click',e=>{if(!e.target.closest?.('#suggestPopover'))closeSuggest()});
window.PreviewSmart={runRefinement,refresh:()=>renderRefinement([])};