import {aiJson} from './ai-client.js';
import {extractJson} from './ai-agent-core.js';
import {fastSuggestionItems,normalizeSmartInput,synonymsFor} from './smart-tools-core.mjs';
import {inferCefr} from './vocabulary-core.mjs';
import {getExternalSuggestions} from './collocation-sources.mjs';
const DATA_KEY='english-collocations-preview-v2';let timer=0,sourceTimer=0,activeRequest=0,suggestCell=null,suggestValues=[],suggestIndex=0;
const esc=value=>String(value??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function readRows(){try{const v=JSON.parse(localStorage.getItem(DATA_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function existingPhrase(phrase){const key=String(phrase||'').trim().toLowerCase();return readRows().some(r=>String(r?.c||'').trim().toLowerCase()===key)}
function parseArray(text){try{const clean=String(text||'').replace(/^```(?:json|text)?\s*/i,'').replace(/\s*```$/,'').trim(),match=clean.match(/\[[\s\S]*\]/),value=JSON.parse(match?match[0]:clean);return Array.isArray(value)?value:[]}catch{return[]}}
function styles(){if(document.getElementById('smartStyles'))return;const s=document.createElement('style');s.id='smartStyles';s.textContent='.suggest-popover{position:fixed;z-index:100003;width:min(410px,calc(100vw - 16px));background:var(--card);border:1px solid var(--line);border-radius:12px;box-shadow:0 18px 50px #0008;padding:8px}.suggest-head{font-size:10px;color:var(--muted);padding:2px 3px 6px}.suggest-list{display:grid;gap:4px;max-height:360px;overflow:auto}.suggestion-btn{width:100%;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:9px;align-items:center;text-align:left;background:var(--card2);border:1px solid var(--line);color:var(--text);border-radius:8px;padding:7px 8px;font-size:10px;cursor:pointer}.suggestion-btn:hover,.suggestion-btn.active{border-color:var(--blue);background:var(--input)}.suggestion-btn.is-existing{border-color:#8a5826;background:#2f271b}.suggestion-btn:disabled{opacity:.8;cursor:default}.suggestion-copy{min-width:0}.suggestion-phrase{font-weight:850;line-height:1.35}.suggestion-meaning{color:var(--muted);font-size:9px;line-height:1.35;margin-top:2px}.suggestion-meta{display:flex;align-items:center;gap:4px;margin-top:3px;flex-wrap:wrap}.suggestion-cefr{padding:1px 4px;border:1px solid var(--line);border-radius:5px;color:var(--blue);font-size:8px;font-weight:900}.suggestion-exists{padding:1px 4px;border:1px solid #8a5826;border-radius:5px;color:#ffbd73;font-size:8px;font-weight:800}.suggestion-arrow{color:var(--muted);font-size:12px}.suggest-note{font-size:9px;color:var(--muted);padding:6px 3px 1px}.suggest-loading{padding:7px 3px;font-size:9px;color:var(--muted)}body.light-theme .suggestion-btn.is-existing{background:#fff7ed;border-color:#fdba74}';document.head.appendChild(s)}
function closeSuggest(){document.getElementById('suggestPopover')?.remove();suggestCell=null;suggestValues=[];suggestIndex=0}
function repositionSuggest(){const pop=document.getElementById('suggestPopover');if(!pop||!suggestCell)return;if(!document.contains(suggestCell)){closeSuggest();return}const r=suggestCell.getBoundingClientRect(),w=pop.offsetWidth,h=pop.offsetHeight;pop.style.left=Math.min(Math.max(8,r.left),Math.max(8,innerWidth-w-8))+'px';const below=r.bottom+5,above=r.top-h-5;pop.style.top=Math.max(8,Math.min(below+h<=innerHeight-8?below:above,innerHeight-h-8))+'px'}
function setActiveSuggestion(index){const buttons=[...document.querySelectorAll('#suggestPopover .suggestion-btn:not(:disabled)')];if(!buttons.length)return;suggestIndex=(index+buttons.length)%buttons.length;buttons.forEach((b,i)=>{const active=i===suggestIndex;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))});buttons[suggestIndex]?.scrollIntoView({block:'nearest'})}
function fill(cell,value,cefr=''){if(!cell||!document.contains(cell))return;cell.textContent=String(value).trim();if(cefr)cell.dataset.suggestCefr=String(cefr).trim();cell.dispatchEvent(new Event('input',{bubbles:true}));cell.focus();cell.blur();closeSuggest()}
function buildItems(raw){const table=readRows();return (Array.isArray(raw)?raw:[]).map((item,index)=>{const phrase=String(item?.c??item?.collocation??item?.phrase??item?.word??'').trim();return {c:phrase,v:String(item?.v??item?.meaningVi??item?.meaning??'').trim(),cefr:String(item?.cefr||inferCefr(phrase)),score:Number(item?.score)||0,source:String(item?.source||'local'),sourceIndex:Number(item?.sourceIndex??index)}}).filter(x=>x.c).map(x=>({...x,exists:table.some(r=>String(r?.c||'').trim().toLowerCase()===x.c.toLowerCase())})).reduce((out,item)=>{const key=item.c.toLowerCase(),old=out.find(x=>x.c.toLowerCase()===key);if(!old)out.push(item);else if(item.score>old.score)Object.assign(old,item);return out},[]).sort((a,b)=>(b.score-a.score)||(a.sourceIndex-b.sourceIndex)).slice(0,20)}
function showSuggestions(cell,raw,label='📚 Gợi ý trong thư viện',loadingMore=false){const clean=buildItems(raw);if(!clean.length&&!loadingMore){closeSuggest();return}let pop=document.getElementById('suggestPopover');if(!pop){pop=document.createElement('div');pop.id='suggestPopover';pop.className='suggest-popover';pop.setAttribute('role','listbox');document.body.appendChild(pop)}suggestCell=cell;suggestValues=clean.filter(x=>!x.exists).map(x=>x.c);suggestIndex=Math.min(suggestIndex,Math.max(0,suggestValues.length-1));pop.innerHTML='';const head=document.createElement('div');head.className='suggest-head';head.textContent=label;pop.appendChild(head);const list=document.createElement('div');list.className='suggest-list';clean.forEach((item,index)=>{const b=document.createElement('button');b.type='button';b.className='suggestion-btn'+(item.exists?' is-existing':'');b.setAttribute('role','option');b.setAttribute('aria-selected',String(index===suggestIndex));if(item.exists)b.disabled=true;b.innerHTML='<span class="suggestion-copy"><span class="suggestion-phrase">'+esc(item.c)+'</span>'+(item.v?'<span class="suggestion-meaning">'+esc(item.v)+'</span>':'')+'<span class="suggestion-meta"><span class="suggestion-cefr">'+esc(item.cefr)+'</span>'+(item.exists?'<span class="suggestion-exists">✓ Đã có trong bảng</span>':'')+'</span></span><span class="suggestion-arrow">'+(item.exists?'✓':'→')+'</span>';b.addEventListener('mousedown',e=>e.preventDefault());if(!item.exists)b.addEventListener('click',()=>fill(cell,item.c,item.cefr));list.appendChild(b)});pop.appendChild(list);if(loadingMore){const load=document.createElement('div');load.className='suggest-loading';load.textContent='🧠 Đang tìm thêm từ Library / Datamuse / AI…';pop.appendChild(load)}const syn=synonymsFor(cell.textContent||'');if(syn.length&&!loadingMore){const sh=document.createElement('div');sh.className='suggest-head';sh.textContent='🔁 Từ gần nghĩa';pop.appendChild(sh);const sv=document.createElement('div');sv.className='suggest-note';sv.textContent=syn.join(' · ');pop.appendChild(sv)}const note=document.createElement('div');note.className='suggest-note';note.textContent='Nguồn: local library + Datamuse + AI · ↑ ↓ chọn · Enter điền · Esc đóng';pop.appendChild(note);repositionSuggest();setActiveSuggestion(suggestIndex)}
function parseAiSuggestions(text){try{const parsed=extractJson(text);if(Array.isArray(parsed))return parsed;if(Array.isArray(parsed?.items))return parsed.items;return parsed?[parsed]:[]}catch{return[]}}
function sanitizeAiSuggestions(text,value){const q=normalizeSmartInput(value),arr=parseAiSuggestions(text).map((x,index)=>{const phrase=String(x?.collocation??x?.phrase??x?.c??'').trim();return {c:phrase,v:String(x?.meaningVi??x?.meaning??x?.v??'').trim(),cefr:String(x?.cefr||inferCefr(phrase)),source:'ai',sourceIndex:index}}).filter(x=>x.c&&x.c.toLowerCase().startsWith(q));return buildItems(arr)}
async function enrichSuggestions(cell,value,token,base){
  let merged=buildItems(base||[]);
  try{
    const external=await getExternalSuggestions(value,{max:80});
    if(token!==activeRequest||document.activeElement!==cell||!document.contains(cell))return;
    merged=buildItems([...(base||[]),...external]);
    showSuggestions(cell,merged,'📚 Gợi ý trong thư viện',merged.length<10);
  }catch{}
  if(merged.length>=10)return;
  try{
    const raw=await aiJson([
      {role:'system',content:'Return only JSON array with up to 20 common natural English collocations that begin exactly with the supplied input. Mix useful collocation patterns where compatible: verb+noun, adjective+noun, noun+noun, adverb+adjective, verb+preposition, adjective+preposition. Prefer workplace, UI/UX, technology, banking, insurance, business and everyday communication. Every item must include collocation, meaningVi, and CEFR from A1/A2/B1/B2/C1/C2. Never invent awkward phrases. No explanations.'},
      {role:'user',content:value}
    ],{batch:false,purpose:'suggestions',maxNewTokens:384,timeoutMs:20000});
    if(token!==activeRequest||document.activeElement!==cell||!document.contains(cell))return;
    merged=buildItems([...merged,...sanitizeAiSuggestions(raw,value)]);
    showSuggestions(cell,merged,'📚 Gợi ý trong thư viện',false);
  }catch{
    const pop=document.getElementById('suggestPopover');
    if(pop&&token===activeRequest){
      const load=pop.querySelector('.suggest-loading');
      if(load)load.textContent=merged.length?'⚠️ Nguồn mở rộng không khả dụng · vẫn giữ các cụm hiện có':'⚠️ Chưa tìm thêm được · thử lại sau';
    }
  }
}
function requestSuggestions(cell,value,token){
  const local=fastSuggestionItems(value);
  showSuggestions(cell,local,'📚 Gợi ý trong thư viện',local.length<10);
  clearTimeout(sourceTimer);
  sourceTimer=setTimeout(()=>enrichSuggestions(cell,value,token,local),250);
}
function handleInput(e){const cell=e.target.closest?.('.editable[data-field="c"]');if(!cell)return;clearTimeout(timer);clearTimeout(sourceTimer);activeRequest++;closeSuggest();suggestIndex=0;const token=activeRequest,value=String(cell.textContent||'').trim();if(value.length<2)return;timer=setTimeout(()=>requestSuggestions(cell,value,token),120)}
function handleFocus(e){const cell=e.target.closest?.('.editable[data-field="c"]');activeRequest++;clearTimeout(timer);clearTimeout(sourceTimer);closeSuggest();if(!cell)return;const value=String(cell.textContent||'').trim();if(value.length<2)return;requestSuggestions(cell,value,activeRequest)}
function handleKeydown(e){const cell=e.target.closest?.('.editable[data-field="c"]');if(!cell||document.activeElement!==cell||!document.getElementById('suggestPopover'))return;if(e.key==='ArrowDown'){e.preventDefault();e.stopPropagation();setActiveSuggestion(suggestIndex+1)}else if(e.key==='ArrowUp'){e.preventDefault();e.stopPropagation();setActiveSuggestion(suggestIndex-1)}else if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.stopPropagation();const buttons=[...document.querySelectorAll('#suggestPopover .suggestion-btn:not(:disabled)')];const active=buttons[suggestIndex];if(active){active.click()}}else if(e.key==='Escape'){e.preventDefault();e.stopPropagation();activeRequest++;closeSuggest()}}
styles();document.addEventListener('input',handleInput);document.addEventListener('focusin',handleFocus);document.addEventListener('keydown',handleKeydown);document.addEventListener('click',e=>{if(!e.target.closest?.('#suggestPopover')&&!e.target.closest?.('.editable[data-field="c"]')){activeRequest++;clearTimeout(sourceTimer);closeSuggest()}});window.addEventListener('resize',repositionSuggest);window.addEventListener('scroll',repositionSuggest,true);
window.PreviewSmart={refresh:()=>{}};