import {SRS_KEY,SRS_INTERVALS_DAYS,addDaysToDateKey,normalizeState,createCard,removeCard,dueCards,nextDueDate,reviewCard,syncStateRows} from './srs-core.mjs';
import {localDateKey} from './analytics-core.mjs';

const DATA_KEY='english-collocations-preview-v2';
const TODAY=()=>localDateKey();
function load(){try{return normalizeState(JSON.parse(localStorage.getItem(SRS_KEY)||'null'),TODAY())}catch{return {version:1,cards:{}}}}
function save(state){localStorage.setItem(SRS_KEY,JSON.stringify(state));window.dispatchEvent(new CustomEvent('preview-srs-updated'))}
function rows(){try{const v=JSON.parse(localStorage.getItem(DATA_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return []}}
function currentCards(){return syncStateRows(load(),rows(),TODAY())}
function dueCount(){return dueCards(currentCards(),TODAY()).length}

function styles(){if(document.getElementById('srsStyles'))return;const s=document.createElement('style');s.id='srsStyles';s.textContent=`.srs-card{padding:12px}.srs-summary{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:10px}.srs-due{font-size:24px;font-weight:900}.srs-next{font-size:10px;color:var(--muted)}.srs-start{width:100%;margin-top:9px}.srs-note{font-size:9px;color:var(--muted);margin-top:8px}.srs-modal{position:fixed;inset:0;background:#08101dcc;z-index:100002;display:grid;place-items:center;padding:18px}.srs-modal[hidden]{display:none}.srs-panel{width:min(560px,100%);background:var(--card);border:1px solid var(--line);border-radius:18px;box-shadow:0 28px 80px #0009;overflow:hidden}.srs-panel-head{display:flex;align-items:center;justify-content:space-between;padding:13px 15px;border-bottom:1px solid var(--line)}.srs-panel-title{font-weight:850}.srs-panel-count{font-size:10px;color:var(--muted)}.srs-front{padding:28px 20px 18px;text-align:center}.srs-collocation{font-size:25px;font-weight:900;line-height:1.2}.srs-answer{margin-top:14px;padding:12px;border:1px dashed var(--line);border-radius:12px;text-align:left}.srs-answer[hidden]{display:none}.srs-answer b{display:block}.srs-answer p{margin:5px 0 0;color:var(--muted);font-size:11px}.srs-reveal{width:100%}.srs-ratings{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:14px}.srs-ratings button{font-size:10px;padding:8px}.srs-footer{padding:10px 15px;border-top:1px solid var(--line);font-size:9px;color:var(--muted)}@media(max-width:520px){.srs-ratings{grid-template-columns:repeat(2,1fr)}.srs-collocation{font-size:22px}}`;document.head.appendChild(s)}
function cardMarkup(){const anchor=document.getElementById('goalsCard')||document.querySelector('.analytics-card');const card=document.createElement('section');card.id='srsCard';card.className='card srs-card';card.innerHTML='<div class="feature-head"><div><div class="feature-title">🎴 Flashcard · SRS</div><div class="feature-sub">Ôn lại theo nhịp 1 → 3 → 7 → 30 ngày.</div></div></div><div class="srs-summary"><div><div class="srs-due" id="srsDue">0</div><div class="srs-next" id="srsNext">đến hạn hôm nay</div></div><button class="secondary srs-start" id="srsStart" type="button">🎴 Ôn tập</button></div><div class="srs-note">Khi đổi một collocation sang “Đã học”, card sẽ tự được lên lịch ôn sau 1 ngày.</div>';if(anchor)anchor.insertAdjacentElement('afterend',card);else document.querySelector('.sidebar')?.prepend(card);return card}
function ensureModal(){if(document.getElementById('srsModal'))return document.getElementById('srsModal');const m=document.createElement('div');m.id='srsModal';m.className='srs-modal';m.hidden=true;m.innerHTML='<div class="srs-panel" role="dialog" aria-modal="true" aria-labelledby="srsPanelTitle"><div class="srs-panel-head"><div class="srs-panel-title" id="srsPanelTitle">🎴 Ôn tập</div><div class="srs-panel-count" id="srsPanelCount"></div></div><div class="srs-front" id="srsFront"></div><div class="srs-footer">Lịch SRS: '+SRS_INTERVALS_DAYS.join(' → ')+' ngày · dữ liệu lưu trên thiết bị Preview.</div></div>';document.body.appendChild(m);return m}
function refresh(){styles();const card=document.getElementById('srsCard')||cardMarkup(),today=TODAY(),state=currentCards(),due=dueCards(state,today),next=nextDueDate(state,today);card.querySelector('#srsDue').textContent=due.length;card.querySelector('#srsNext').textContent=next?'card tiếp theo: '+next:'không có card kế tiếp';card.querySelector('#srsStart').disabled=!due.length;ensureModal()}
function close(){const m=document.getElementById('srsModal');if(m)m.hidden=true}
function renderCardSession(queue,index=0){const modal=ensureModal(),front=modal.querySelector('#srsFront'),count=modal.querySelector('#srsPanelCount');if(index>=queue.length){close();refresh();return}const state=currentCards(),card=state.cards[queue[index].id];if(!card){queue.splice(index,1);renderCardSession(queue,index);return}const row=rows().find(r=>String(r.id)===String(card?.id));if(!row){queue.splice(index,1);renderCardSession(queue,index);return}count.textContent=(index+1)+' / '+queue.length;front.innerHTML='';const phrase=document.createElement('div');phrase.className='srs-collocation';phrase.textContent=row.c||'';front.appendChild(phrase);const reveal=document.createElement('button');reveal.className='secondary srs-reveal';reveal.type='button';reveal.textContent='👁 Hiện nghĩa & ví dụ';front.appendChild(reveal);const answer=document.createElement('div');answer.className='srs-answer';answer.hidden=true;const meaning=document.createElement('b');meaning.textContent=row.m||'Chưa có nghĩa';answer.appendChild(meaning);const ex=document.createElement('p');ex.textContent=row.e||'Chưa có câu ví dụ';answer.appendChild(ex);front.appendChild(answer);const ratings=document.createElement('div');ratings.className='srs-ratings';ratings.hidden=true;for(const [key,label] of [['again','Lại · 1d'],['hard','Khó'],['good','Tốt'],['easy','Dễ']]){const b=document.createElement('button');b.type='button';b.className=key==='good'?'':'secondary';b.textContent=label;b.addEventListener('click',()=>{const nextState=reviewCard(currentCards(),card.id,key,TODAY());save(nextState);renderCardSession(queue,index+1)});ratings.appendChild(b)}front.appendChild(ratings);reveal.addEventListener('click',()=>{answer.hidden=false;ratings.hidden=false;reveal.hidden=true});modal.hidden=false}
function start(){const queue=dueCards(currentCards(),TODAY());if(queue.length)renderCardSession(queue,0)}
function syncRowsApi(data){const next=syncStateRows(load(),data,TODAY());save(next);refresh()}
function onStatusChange(id,status){if(status==='Đã học'){save(createCard(load(),id,TODAY()))}else{save(removeCard(load(),id,TODAY()))}refresh()}
window.PreviewSRS={getSnapshot:load,restoreSnapshot(value){save(normalizeState(value,TODAY()));refresh()},syncRows:syncRowsApi,onStatusChange,refresh,start};
window.addEventListener('preview-data-updated',e=>{const kind=e.detail?.kind;if(kind==='status'||kind==='collection'||kind==='restore')syncRowsApi(rows())});
window.addEventListener('preview-srs-updated',refresh);
document.addEventListener('click',e=>{if(e.target.closest('#srsStart'))start();if(e.target.closest('#srsClose'))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
refresh();
