const STRUCTURE_MAP=Object.freeze({
  'keep in check':'Keep + something + in check',
  'work on a project':'work on + something',
  'reject a request':'reject + a request',
  'take advantage of':'take advantage of + something',
  'save time':'save + time',
  'allow for':'allow for + something',
  'avoid unnecessary steps':'avoid + noun / doing something',
  'understand the context':'understand + something',
  'make a decision':'make + a decision',
  'take responsibility':'take + responsibility for + something',
  'take ownership':'take ownership of + something',
  'reach an agreement':'reach + an agreement',
  'provide feedback':'provide + someone + with feedback',
  'give feedback':'give + someone + feedback',
  'get feedback':'get + feedback from + someone',
  'ask for feedback':'ask for + feedback',
  'give an update':'give + an update on + something',
  'provide an update':'provide + an update on + something',
  'raise awareness':'raise + awareness of + something',
  'raise a concern':'raise + a concern about + something',
  'address an issue':'address + an issue',
  'resolve an issue':'resolve + an issue',
  'solve a problem':'solve + a problem',
  'identify a problem':'identify + a problem',
  'report a problem':'report + a problem to + someone',
  'fix a bug':'fix + a bug',
  'track a bug':'track + a bug',
  'find a bug':'find + a bug',
  'write a report':'write + a report',
  'review a report':'review + a report',
  'prepare a report':'prepare + a report',
  'submit a report':'submit + a report',
  'conduct research':'conduct + research',
  'do research':'do + research',
  'carry out research':'carry out + research',
  'conduct an analysis':'conduct + an analysis',
  'perform an analysis':'perform + an analysis',
  'analyze data':'analyze + data',
  'collect data':'collect + data',
  'clean data':'clean + data',
  'share data':'share + data with + someone',
  'use data':'use + data to + verb',
  'protect data':'protect + data from + something',
  'secure data':'secure + data from + something',
  'access data':'access + data',
  'manage data':'manage + data',
  'design a user flow':'design + a user flow',
  'map a user journey':'map + a user journey',
  'conduct user research':'conduct + user research',
  'define user needs':'define + user needs',
  'identify user needs':'identify + user needs',
  'gather user feedback':'gather + user feedback',
  'improve usability':'improve + usability',
  'improve the user experience':'improve + the user experience',
  'test a prototype':'test + a prototype',
  'build a prototype':'build + a prototype',
  'create a prototype':'create + a prototype',
  'follow a design system':'follow + a design system',
  'build a design system':'build + a design system',
  'meet a requirement':'meet + a requirement',
  'fulfill a requirement':'fulfill + a requirement',
  'define requirements':'define + requirements',
  'gather requirements':'gather + requirements',
  'prioritize requirements':'prioritize + requirements',
  'set a goal':'set + a goal',
  'set a target':'set + a target',
  'achieve a goal':'achieve + a goal',
  'meet a target':'meet + a target',
  'set a deadline':'set + a deadline',
  'miss a deadline':'miss + a deadline',
  'beat a deadline':'beat + a deadline',
  'manage a project':'manage + a project',
  'run a project':'run + a project',
  'launch a product':'launch + a product',
  'develop a product':'develop + a product',
  'build a product':'build + a product',
  'deliver a product':'deliver + a product',
  'make a payment':'make + a payment',
  'process a payment':'process + a payment',
  'process a loan application':'process + a loan application',
  'open an account':'open + an account',
  'close an account':'close + an account',
  'make a transaction':'make + a transaction',
  'complete a transaction':'complete + a transaction',
  'file a claim':'file + a claim',
  'submit a claim':'submit + a claim',
  'process a claim':'process + a claim',
  'approve a claim':'approve + a claim',
  'reject a claim':'reject + a claim',
  'pay a premium':'pay + a premium',
  'renew a policy':'renew + a policy',
  'issue a policy':'issue + a policy',
  'assess a risk':'assess + a risk',
  'mitigate risk':'mitigate + risk',
  'manage risk':'manage + risk',
  'comply with regulations':'comply with + regulations',
  'ensure compliance':'ensure + compliance',
  'meet compliance requirements':'meet + compliance requirements',
  'attend a meeting':'attend + a meeting',
  'have a meeting':'have + a meeting',
  'hold a meeting':'hold + a meeting',
  'schedule a meeting':'schedule + a meeting',
  'join a meeting':'join + a meeting',
  'lead a meeting':'lead + a meeting',
  'facilitate a meeting':'facilitate + a meeting',
  'discuss an issue':'discuss + an issue',
  'share an idea':'share + an idea',
  'present an idea':'present + an idea',
  'make a suggestion':'make + a suggestion',
  'make a recommendation':'make + a recommendation',
  'make a request':'make + a request',
  'respond to a request':'respond to + a request',
  'follow up on':'follow up on + something',
  'look into an issue':'look into + an issue',
  'look for a solution':'look for + a solution',
  'come up with a solution':'come up with + a solution',
  'find a solution':'find + a solution',
  'work with a team':'work with + a team',
  'work from home':'work from home',
  'work under pressure':'work under + pressure',
  'deal with a customer':'deal with + a customer',
  'help a customer':'help + a customer',
  'support a customer':'support + a customer',
  'answer a question':'answer + a question',
  'ask a question':'ask + a question',
  'give advice':'give + advice',
  'ask for help':'ask for + help',
  'make progress':'make + progress',
  'keep track of':'keep track of + something',
  'keep up with':'keep up with + something',
  'keep an eye on':'keep an eye on + something',
  'pay attention to':'pay attention to + something',
  'take notes':'take + notes',
  'take a break':'take + a break',
  'make an appointment':'make + an appointment',
  'cancel an appointment':'cancel + an appointment',
  'book a flight':'book + a flight',
  'book a hotel':'book + a hotel',
  'catch a flight':'catch + a flight',
  'miss a flight':'miss + a flight',
  'take a taxi':'take + a taxi',
  'catch a bus':'catch + a bus',
  'take a train':'take + a train',
  'make a reservation':'make + a reservation',
  'place an order':'place + an order',
  'cancel an order':'cancel + an order',
  'return a product':'return + a product',
  'ask for a refund':'ask for + a refund',
  'try on clothes':'try on + clothes',
  'pay by card':'pay by + card',
  'pay in cash':'pay in + cash',
  'cook a meal':'cook + a meal',
  'prepare a meal':'prepare + a meal',
  'have breakfast':'have + breakfast',
  'have lunch':'have + lunch',
  'have dinner':'have + dinner',
  'get some sleep':'get + some sleep',
  'get enough sleep':'get + enough sleep',
  'get some exercise':'get + some exercise',
  'go for a walk':'go for + a walk',
  'go for a run':'go for + a run',
  'ride a bike':'ride + a bike',
  'keep fit':'keep + fit',
  'stay healthy':'stay + healthy',
  'catch a cold':'catch + a cold',
  'take medicine':'take + medicine',
  'make a complaint':'make + a complaint',
  'file a complaint':'file + a complaint',
  'break the law':'break + the law',
  'obey the law':'obey + the law',
  'pay a fine':'pay + a fine',
  'save money':'save + money',
  'spend money':'spend + money',
  'make money':'make + money',
  'make an effort':'make + an effort',
  'take action':'take + action',
  'take a risk':'take + a risk',
  'avoid a risk':'avoid + a risk'
});
export function normalizeStructure(value){return String(value??'').replace(/\s+/g,' ').trim().slice(0,240)}
export function inferStructure(collocation){
  const raw=String(collocation??'').replace(/\s+/g,' ').trim(),key=raw.toLowerCase();
  if(!raw)return '';
  if(STRUCTURE_MAP[key])return STRUCTURE_MAP[key];
  const words=raw.split(' '),head=words[0]?.toLowerCase()||'';
  const prepIndex=words.findIndex(w=>['in','on','at','for','of','to','with','from','about','under','over'].includes(w.toLowerCase()));
  if(prepIndex>0)return words.slice(0,prepIndex).join(' ')+' '+words[prepIndex]+' + something';
  if(['make','take','give','have','get','keep','do','set','meet','reach','provide','raise','save','use','build','create','write','review','prepare','submit','reject','allow','avoid','manage','support','develop','launch','process','close','open','approve','pay','renew','issue','assess','fix','track','find','share','collect','clean','secure','access','protect','analyze','map','test','define','gather','prioritize','achieve','miss','beat','attend','schedule','join','lead','discuss','present','ask','answer','cancel','return','cook','ride','spend'].includes(head))return head+' + something';
  return '';
}
